<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.13"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>Qt: HLine Class Reference</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Qt
   &#160;<span id="projectnumber">1.0</span>
   </div>
   <div id="projectbrief">Specific widgets for Qt</div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('dc/ddf/a00067.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="../../df/d5f/a00064.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">HLine Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>Create a horizontal line.  
 <a href="../../dc/ddf/a00067.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="../../da/d45/a00011_source.php">Lines.hpp</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for HLine:</div>
<div class="dyncontent">
<div class="center"><img src="../../d9/db3/a00066.png" border="0" usemap="#HLine_inherit__map" alt="Inheritance graph"/></div>
<map name="HLine_inherit__map" id="HLine_inherit__map">
<area shape="rect" id="node2" href="../../d1/d6f/a00063.php" title="Create a line. " alt="" coords="17,80,63,107"/>
</map>
<center><span class="legend">[<a target="top" href="../../graph_legend.php">legend</a>]</span></center></div>
<div class="dynheader">
Collaboration diagram for HLine:</div>
<div class="dyncontent">
<div class="center"><img src="../../de/de1/a00065.png" border="0" usemap="#HLine_coll__map" alt="Collaboration graph"/></div>
<map name="HLine_coll__map" id="HLine_coll__map">
<area shape="rect" id="node2" href="../../d1/d6f/a00063.php" title="Create a line. " alt="" coords="17,80,63,107"/>
</map>
<center><span class="legend">[<a target="top" href="../../graph_legend.php">legend</a>]</span></center></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:aa48630fb2b4fd09dbb4f03fd23f8dc9c"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/ddf/a00067.php#aa48630fb2b4fd09dbb4f03fd23f8dc9c">HLine</a> (QWidget *parent=nullptr)</td></tr>
<tr class="memdesc:aa48630fb2b4fd09dbb4f03fd23f8dc9c"><td class="mdescLeft">&#160;</td><td class="mdescRight">Create a <a class="el" href="../../dc/ddf/a00067.php" title="Create a horizontal line. ">HLine</a>.  <a href="#aa48630fb2b4fd09dbb4f03fd23f8dc9c">More...</a><br /></td></tr>
<tr class="separator:aa48630fb2b4fd09dbb4f03fd23f8dc9c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac107cd8335137b912fe56c3dc18763b0"><td class="memItemLeft" align="right" valign="top">virtual&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/ddf/a00067.php#ac107cd8335137b912fe56c3dc18763b0">~HLine</a> ()</td></tr>
<tr class="separator:ac107cd8335137b912fe56c3dc18763b0"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pub_methods_a00063"><td colspan="2" onclick="javascript:toggleInherit('pub_methods_a00063')"><img src="../../closed.png" alt="-"/>&#160;Public Member Functions inherited from <a class="el" href="../../d1/d6f/a00063.php">Line</a></td></tr>
<tr class="memitem:a5bc71a96071093bc00a3ad5d58526b99 inherit pub_methods_a00063"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d1/d6f/a00063.php#a5bc71a96071093bc00a3ad5d58526b99">Line</a> (QWidget *parent, QFrame::Shape shape)</td></tr>
<tr class="memdesc:a5bc71a96071093bc00a3ad5d58526b99 inherit pub_methods_a00063"><td class="mdescLeft">&#160;</td><td class="mdescRight">Create a <a class="el" href="../../d1/d6f/a00063.php" title="Create a line. ">Line</a>.  <a href="../../d1/d6f/a00063.php#a5bc71a96071093bc00a3ad5d58526b99">More...</a><br /></td></tr>
<tr class="separator:a5bc71a96071093bc00a3ad5d58526b99 inherit pub_methods_a00063"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4a95bafcefa28672b3999deb011b9e50 inherit pub_methods_a00063"><td class="memItemLeft" align="right" valign="top">virtual&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d1/d6f/a00063.php#a4a95bafcefa28672b3999deb011b9e50">~Line</a> ()</td></tr>
<tr class="separator:a4a95bafcefa28672b3999deb011b9e50 inherit pub_methods_a00063"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>Create a horizontal line. </p>

<p class="definition">Definition at line <a class="el" href="../../da/d45/a00011_source.php#l00029">29</a> of file <a class="el" href="../../da/d45/a00011_source.php">Lines.hpp</a>.</p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a id="aa48630fb2b4fd09dbb4f03fd23f8dc9c"></a>
<h2 class="memtitle"><span class="permalink"><a href="#aa48630fb2b4fd09dbb4f03fd23f8dc9c">&#9670;&nbsp;</a></span>HLine()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">HLine::HLine </td>
          <td>(</td>
          <td class="paramtype">QWidget *&#160;</td>
          <td class="paramname"><em>parent</em> = <code>nullptr</code></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Create a <a class="el" href="../../dc/ddf/a00067.php" title="Create a horizontal line. ">HLine</a>. </p>

<p class="definition">Definition at line <a class="el" href="../../da/d45/a00011_source.php#l00033">33</a> of file <a class="el" href="../../da/d45/a00011_source.php">Lines.hpp</a>.</p>

</div>
</div>
<a id="ac107cd8335137b912fe56c3dc18763b0"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ac107cd8335137b912fe56c3dc18763b0">&#9670;&nbsp;</a></span>~HLine()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">virtual HLine::~HLine </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span><span class="mlabel">virtual</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p class="definition">Definition at line <a class="el" href="../../da/d45/a00011_source.php#l00034">34</a> of file <a class="el" href="../../da/d45/a00011_source.php">Lines.hpp</a>.</p>

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li><a class="el" href="../../da/d45/a00011_source.php">Lines.hpp</a></li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="../../dc/ddf/a00067.php">HLine</a></li>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.13 </li>
  </ul>
</div>
</body>
</html>
