<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.13"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>Qt: Member List</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Qt
   &#160;<span id="projectnumber">1.0</span>
   </div>
   <div id="projectbrief">Specific widgets for Qt</div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('db/df8/a00076.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="headertitle">
<div class="title">TableWidget Member List</div>  </div>
</div><!--header-->
<div class="contents">

<p>This is the complete list of members for <a class="el" href="../../db/df8/a00076.php">TableWidget</a>, including all inherited members.</p>
<table class="directory">
  <tr class="even"><td class="entry"><a class="el" href="../../db/df8/a00076.php#abe173d2bf4af78a34eea42f6015dfc24">add</a>(QWidget *widget)</td><td class="entry"><a class="el" href="../../db/df8/a00076.php">TableWidget</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../db/df8/a00076.php#acce74e5071c06cb79eb9120e7ca321f2">add</a>(QCheckBox *widget)</td><td class="entry"><a class="el" href="../../db/df8/a00076.php">TableWidget</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../db/df8/a00076.php#a89b038bcb974698aa762291d72cb52e3">add</a>(QWidget *widget, size_t x, size_t y)</td><td class="entry"><a class="el" href="../../db/df8/a00076.php">TableWidget</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../db/df8/a00076.php#a9965d8f6b70b52fc8e25906a20d4a771">addHeader</a>(QWidget *widget)</td><td class="entry"><a class="el" href="../../db/df8/a00076.php">TableWidget</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../db/df8/a00076.php#a59d73338e3d97bafc754ed798fd487f6">addHeader</a>(QWidget *widget, size_t x)</td><td class="entry"><a class="el" href="../../db/df8/a00076.php">TableWidget</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../db/df8/a00076.php#a6ec3251ece680a9da68c7e4adb1f6531">get</a>(size_t w=0, size_t h=0)</td><td class="entry"><a class="el" href="../../db/df8/a00076.php">TableWidget</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../da/dec/a00080.php#a0ce51928b65b53bd72575e7138e3238c">paintEvent</a>(QPaintEvent *event)</td><td class="entry"><a class="el" href="../../da/dec/a00080.php">Widget</a></td><td class="entry"><span class="mlabel">protected</span><span class="mlabel">virtual</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../db/df8/a00076.php#a38b92f2d6e93627e3034f07a73138b1e">set</a>(QWidget *widget, size_t x, size_t y)</td><td class="entry"><a class="el" href="../../db/df8/a00076.php">TableWidget</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../db/df8/a00076.php#a25bba3124cdbe518985157ff23b0b1d0">setHeader</a>(QWidget *widget, size_t x)</td><td class="entry"><a class="el" href="../../db/df8/a00076.php">TableWidget</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../db/df8/a00076.php#aa29e2c37c0e310779790537890c529f2">TableWidget</a>(QWidget *parent=nullptr, size_t w=0, size_t h=0)</td><td class="entry"><a class="el" href="../../db/df8/a00076.php">TableWidget</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../db/df8/a00076.php#a8ee97e18b4afb72672b36ef2002537ae">update</a>()</td><td class="entry"><a class="el" href="../../db/df8/a00076.php">TableWidget</a></td><td class="entry"><span class="mlabel">protected</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../da/dec/a00080.php#ace1aa23652eb4425355a81760b39fd37">Widget</a>(QWidget *parent=nullptr)</td><td class="entry"><a class="el" href="../../da/dec/a00080.php">Widget</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../db/df8/a00076.php#a5fb6edc429e21280d8f47faf6fe012fa">~TableWidget</a>()</td><td class="entry"><a class="el" href="../../db/df8/a00076.php">TableWidget</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../da/dec/a00080.php#a714cf798aadb4d615f6f60a355382c02">~Widget</a>()</td><td class="entry"><a class="el" href="../../da/dec/a00080.php">Widget</a></td><td class="entry"><span class="mlabel">inline</span><span class="mlabel">virtual</span></td></tr>
</table></div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.13 </li>
  </ul>
</div>
</body>
</html>
