<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.13"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>Qt: WindowButton Class Reference</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Qt
   &#160;<span id="projectnumber">1.0</span>
   </div>
   <div id="projectbrief">Specific widgets for Qt</div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d5/d1e/a00103.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#pub-types">Public Types</a> &#124;
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pro-types">Protected Types</a> &#124;
<a href="#pro-methods">Protected Member Functions</a> &#124;
<a href="../../d0/d61/a00100.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">WindowButton Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>The buttons for the <a class="el" href="../../df/d98/a00107.php" title="The titlebar of the Window class. ">WindowTitleBar</a> and the <a class="el" href="../../da/d74/a00099.php" title="A custom window. ">Window</a>.  
 <a href="../../d5/d1e/a00103.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="../../dd/d32/a00041_source.php">WindowButton.hpp</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for WindowButton:</div>
<div class="dyncontent">
<div class="center"><img src="../../d9/dcc/a00102.png" border="0" usemap="#WindowButton_inherit__map" alt="Inheritance graph"/></div>
<center><span class="legend">[<a target="top" href="../../graph_legend.php">legend</a>]</span></center></div>
<div class="dynheader">
Collaboration diagram for WindowButton:</div>
<div class="dyncontent">
<div class="center"><img src="../../d4/d3a/a00101.png" border="0" usemap="#WindowButton_coll__map" alt="Collaboration graph"/></div>
<center><span class="legend">[<a target="top" href="../../graph_legend.php">legend</a>]</span></center></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-types"></a>
Public Types</h2></td></tr>
<tr class="memitem:a1a23c44a782fc06df076f22ea249084b"><td class="memItemLeft" align="right" valign="top">enum &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d5/d1e/a00103.php#a1a23c44a782fc06df076f22ea249084b">ButtonType</a> { <a class="el" href="../../d5/d1e/a00103.php#a1a23c44a782fc06df076f22ea249084ba6f1f4ad27fa2618744b86d9b8bd2ab1d">BUTTON_MINIMIZE</a>, 
<a class="el" href="../../d5/d1e/a00103.php#a1a23c44a782fc06df076f22ea249084ba1acf7aace7390523e419dcce457ca1f0">BUTTON_MAXIMIZE</a>, 
<a class="el" href="../../d5/d1e/a00103.php#a1a23c44a782fc06df076f22ea249084baed872b32ab60b3aae044fdf829766e74">BUTTON_CLOSE</a>
 }<tr class="memdesc:a1a23c44a782fc06df076f22ea249084b"><td class="mdescLeft">&#160;</td><td class="mdescRight">The differents buttons type.  <a href="../../d5/d1e/a00103.php#a1a23c44a782fc06df076f22ea249084b">More...</a><br /></td></tr>
</td></tr>
<tr class="separator:a1a23c44a782fc06df076f22ea249084b"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:ac4f0b135bb2c7d7a301c8ccd8ed14ef0"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d5/d1e/a00103.php#ac4f0b135bb2c7d7a301c8ccd8ed14ef0">WindowButton</a> (<a class="el" href="../../d5/d1e/a00103.php#a1a23c44a782fc06df076f22ea249084b">ButtonType</a> type, QWidget *parent=nullptr)</td></tr>
<tr class="memdesc:ac4f0b135bb2c7d7a301c8ccd8ed14ef0"><td class="mdescLeft">&#160;</td><td class="mdescRight">The constructor.  <a href="#ac4f0b135bb2c7d7a301c8ccd8ed14ef0">More...</a><br /></td></tr>
<tr class="separator:ac4f0b135bb2c7d7a301c8ccd8ed14ef0"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af6a0e6f87bae8c50d9d2e57b371a548a"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d5/d1e/a00103.php#af6a0e6f87bae8c50d9d2e57b371a548a">~WindowButton</a> ()</td></tr>
<tr class="separator:af6a0e6f87bae8c50d9d2e57b371a548a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4babac31336534efca737c5f73710c1d"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d5/d1e/a00103.php#a4babac31336534efca737c5f73710c1d">setNormalColor</a> (int r, int g, int b, int a=255)</td></tr>
<tr class="memdesc:a4babac31336534efca737c5f73710c1d"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the normal color of the button lines.  <a href="#a4babac31336534efca737c5f73710c1d">More...</a><br /></td></tr>
<tr class="separator:a4babac31336534efca737c5f73710c1d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a6947ea55943b909c1d492ad2f79ae1f8"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d5/d1e/a00103.php#a6947ea55943b909c1d492ad2f79ae1f8">setHoveredColor</a> (int r, int g, int b, int a=255)</td></tr>
<tr class="memdesc:a6947ea55943b909c1d492ad2f79ae1f8"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the hovered color of the button lines.  <a href="#a6947ea55943b909c1d492ad2f79ae1f8">More...</a><br /></td></tr>
<tr class="separator:a6947ea55943b909c1d492ad2f79ae1f8"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7a087338372f7592853b050d168df152"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d5/d1e/a00103.php#a7a087338372f7592853b050d168df152">setClickedColor</a> (int r, int g, int b, int a=255)</td></tr>
<tr class="memdesc:a7a087338372f7592853b050d168df152"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the clicked color of the button lines.  <a href="#a7a087338372f7592853b050d168df152">More...</a><br /></td></tr>
<tr class="separator:a7a087338372f7592853b050d168df152"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac7b9d8d3e328e0285ef4664e20acb8d3"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d5/d1e/a00103.php#ac7b9d8d3e328e0285ef4664e20acb8d3">setBackground</a> (int r, int g, int b, int a=255)</td></tr>
<tr class="memdesc:ac7b9d8d3e328e0285ef4664e20acb8d3"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the background color of the button.  <a href="#ac7b9d8d3e328e0285ef4664e20acb8d3">More...</a><br /></td></tr>
<tr class="separator:ac7b9d8d3e328e0285ef4664e20acb8d3"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a434a8192bfe4dea8c7b4e1b052a1a943"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d5/d1e/a00103.php#a434a8192bfe4dea8c7b4e1b052a1a943">setGradient</a> (int r1, int g1, int b1, int a1, int r2, int g2, int b2, int a2)</td></tr>
<tr class="memdesc:a434a8192bfe4dea8c7b4e1b052a1a943"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the gradient background color of the button.  <a href="#a434a8192bfe4dea8c7b4e1b052a1a943">More...</a><br /></td></tr>
<tr class="separator:a434a8192bfe4dea8c7b4e1b052a1a943"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pro-types"></a>
Protected Types</h2></td></tr>
<tr class="memitem:a52e7cf1fa9d4c97891ac0080c65dd57e"><td class="memItemLeft" align="right" valign="top">enum &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d5/d1e/a00103.php#a52e7cf1fa9d4c97891ac0080c65dd57e">ButtonState</a> { <a class="el" href="../../d5/d1e/a00103.php#a52e7cf1fa9d4c97891ac0080c65dd57ea802952130e11d0d17a6d8cb3b202ba97">STATE_NORMAL</a>, 
<a class="el" href="../../d5/d1e/a00103.php#a52e7cf1fa9d4c97891ac0080c65dd57eaed6a113e687faedcd480bb6c24742b0e">STATE_HOVERED</a>, 
<a class="el" href="../../d5/d1e/a00103.php#a52e7cf1fa9d4c97891ac0080c65dd57ea22e18925772fb70a02ef5f93fd3f8be7">STATE_CLICKED</a>
 }<tr class="memdesc:a52e7cf1fa9d4c97891ac0080c65dd57e"><td class="mdescLeft">&#160;</td><td class="mdescRight">The differents buttons states.  <a href="../../d5/d1e/a00103.php#a52e7cf1fa9d4c97891ac0080c65dd57e">More...</a><br /></td></tr>
</td></tr>
<tr class="separator:a52e7cf1fa9d4c97891ac0080c65dd57e"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pro-methods"></a>
Protected Member Functions</h2></td></tr>
<tr class="memitem:a2dd52661908250a571804fe967bcd316"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d5/d1e/a00103.php#a2dd52661908250a571804fe967bcd316">resizeEvent</a> (QResizeEvent *event)</td></tr>
<tr class="memdesc:a2dd52661908250a571804fe967bcd316"><td class="mdescLeft">&#160;</td><td class="mdescRight">The resize event of the button.  <a href="#a2dd52661908250a571804fe967bcd316">More...</a><br /></td></tr>
<tr class="separator:a2dd52661908250a571804fe967bcd316"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9d63cf19bcf3f8ba8a7f03fe4f222f11"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d5/d1e/a00103.php#a9d63cf19bcf3f8ba8a7f03fe4f222f11">paintEvent</a> (QPaintEvent *event)</td></tr>
<tr class="memdesc:a9d63cf19bcf3f8ba8a7f03fe4f222f11"><td class="mdescLeft">&#160;</td><td class="mdescRight">The paint event of the button.  <a href="#a9d63cf19bcf3f8ba8a7f03fe4f222f11">More...</a><br /></td></tr>
<tr class="separator:a9d63cf19bcf3f8ba8a7f03fe4f222f11"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aab556dedddbb1c9832f572b747449055"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d5/d1e/a00103.php#aab556dedddbb1c9832f572b747449055">enterEvent</a> (QEvent *event)</td></tr>
<tr class="memdesc:aab556dedddbb1c9832f572b747449055"><td class="mdescLeft">&#160;</td><td class="mdescRight">The enter event of the button.  <a href="#aab556dedddbb1c9832f572b747449055">More...</a><br /></td></tr>
<tr class="separator:aab556dedddbb1c9832f572b747449055"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8a89e083618d2f239a60bf5adb7c79a2"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d5/d1e/a00103.php#a8a89e083618d2f239a60bf5adb7c79a2">leaveEvent</a> (QEvent *event)</td></tr>
<tr class="memdesc:a8a89e083618d2f239a60bf5adb7c79a2"><td class="mdescLeft">&#160;</td><td class="mdescRight">The leave event of the button.  <a href="#a8a89e083618d2f239a60bf5adb7c79a2">More...</a><br /></td></tr>
<tr class="separator:a8a89e083618d2f239a60bf5adb7c79a2"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af7caa976fc5766ddc3d89eef1965a9c6"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d5/d1e/a00103.php#af7caa976fc5766ddc3d89eef1965a9c6">mousePressEvent</a> (QMouseEvent *event)</td></tr>
<tr class="memdesc:af7caa976fc5766ddc3d89eef1965a9c6"><td class="mdescLeft">&#160;</td><td class="mdescRight">The mouse press event of the button.  <a href="#af7caa976fc5766ddc3d89eef1965a9c6">More...</a><br /></td></tr>
<tr class="separator:af7caa976fc5766ddc3d89eef1965a9c6"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:afd414539e6cf2fc7072a175032a6f1ff"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d5/d1e/a00103.php#afd414539e6cf2fc7072a175032a6f1ff">mouseReleaseEvent</a> (QMouseEvent *event)</td></tr>
<tr class="memdesc:afd414539e6cf2fc7072a175032a6f1ff"><td class="mdescLeft">&#160;</td><td class="mdescRight">The mouse release event of the button.  <a href="#afd414539e6cf2fc7072a175032a6f1ff">More...</a><br /></td></tr>
<tr class="separator:afd414539e6cf2fc7072a175032a6f1ff"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>The buttons for the <a class="el" href="../../df/d98/a00107.php" title="The titlebar of the Window class. ">WindowTitleBar</a> and the <a class="el" href="../../da/d74/a00099.php" title="A custom window. ">Window</a>. </p>

<p class="definition">Definition at line <a class="el" href="../../dd/d32/a00041_source.php#l00018">18</a> of file <a class="el" href="../../dd/d32/a00041_source.php">WindowButton.hpp</a>.</p>
</div><h2 class="groupheader">Member Enumeration Documentation</h2>
<a id="a52e7cf1fa9d4c97891ac0080c65dd57e"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a52e7cf1fa9d4c97891ac0080c65dd57e">&#9670;&nbsp;</a></span>ButtonState</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">enum <a class="el" href="../../d5/d1e/a00103.php#a52e7cf1fa9d4c97891ac0080c65dd57e">WindowButton::ButtonState</a></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>The differents buttons states. </p>
<table class="fieldtable">
<tr><th colspan="2">Enumerator</th></tr><tr><td class="fieldname"><a id="a52e7cf1fa9d4c97891ac0080c65dd57ea802952130e11d0d17a6d8cb3b202ba97"></a>STATE_NORMAL&#160;</td><td class="fielddoc"></td></tr>
<tr><td class="fieldname"><a id="a52e7cf1fa9d4c97891ac0080c65dd57eaed6a113e687faedcd480bb6c24742b0e"></a>STATE_HOVERED&#160;</td><td class="fielddoc"></td></tr>
<tr><td class="fieldname"><a id="a52e7cf1fa9d4c97891ac0080c65dd57ea22e18925772fb70a02ef5f93fd3f8be7"></a>STATE_CLICKED&#160;</td><td class="fielddoc"></td></tr>
</table>

<p class="definition">Definition at line <a class="el" href="../../dd/d32/a00041_source.php#l00089">89</a> of file <a class="el" href="../../dd/d32/a00041_source.php">WindowButton.hpp</a>.</p>

</div>
</div>
<a id="a1a23c44a782fc06df076f22ea249084b"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a1a23c44a782fc06df076f22ea249084b">&#9670;&nbsp;</a></span>ButtonType</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">enum <a class="el" href="../../d5/d1e/a00103.php#a1a23c44a782fc06df076f22ea249084b">WindowButton::ButtonType</a></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>The differents buttons type. </p>
<table class="fieldtable">
<tr><th colspan="2">Enumerator</th></tr><tr><td class="fieldname"><a id="a1a23c44a782fc06df076f22ea249084ba6f1f4ad27fa2618744b86d9b8bd2ab1d"></a>BUTTON_MINIMIZE&#160;</td><td class="fielddoc"></td></tr>
<tr><td class="fieldname"><a id="a1a23c44a782fc06df076f22ea249084ba1acf7aace7390523e419dcce457ca1f0"></a>BUTTON_MAXIMIZE&#160;</td><td class="fielddoc"></td></tr>
<tr><td class="fieldname"><a id="a1a23c44a782fc06df076f22ea249084baed872b32ab60b3aae044fdf829766e74"></a>BUTTON_CLOSE&#160;</td><td class="fielddoc"></td></tr>
</table>

<p class="definition">Definition at line <a class="el" href="../../dd/d32/a00041_source.php#l00022">22</a> of file <a class="el" href="../../dd/d32/a00041_source.php">WindowButton.hpp</a>.</p>

</div>
</div>
<h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a id="ac4f0b135bb2c7d7a301c8ccd8ed14ef0"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ac4f0b135bb2c7d7a301c8ccd8ed14ef0">&#9670;&nbsp;</a></span>WindowButton()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">WindowButton::WindowButton </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="../../d5/d1e/a00103.php#a1a23c44a782fc06df076f22ea249084b">ButtonType</a>&#160;</td>
          <td class="paramname"><em>type</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">QWidget *&#160;</td>
          <td class="paramname"><em>parent</em> = <code>nullptr</code>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>The constructor. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">type</td><td>The type of the button as <b>ButtonType</b> </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">parent</td><td>The parent widget </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a id="af6a0e6f87bae8c50d9d2e57b371a548a"></a>
<h2 class="memtitle"><span class="permalink"><a href="#af6a0e6f87bae8c50d9d2e57b371a548a">&#9670;&nbsp;</a></span>~WindowButton()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">WindowButton::~WindowButton </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a id="aab556dedddbb1c9832f572b747449055"></a>
<h2 class="memtitle"><span class="permalink"><a href="#aab556dedddbb1c9832f572b747449055">&#9670;&nbsp;</a></span>enterEvent()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void WindowButton::enterEvent </td>
          <td>(</td>
          <td class="paramtype">QEvent *&#160;</td>
          <td class="paramname"><em>event</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>The enter event of the button. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">event</td><td>The event to treat </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

</div>
</div>
<a id="a8a89e083618d2f239a60bf5adb7c79a2"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a8a89e083618d2f239a60bf5adb7c79a2">&#9670;&nbsp;</a></span>leaveEvent()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void WindowButton::leaveEvent </td>
          <td>(</td>
          <td class="paramtype">QEvent *&#160;</td>
          <td class="paramname"><em>event</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>The leave event of the button. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">event</td><td>The event to treat </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

</div>
</div>
<a id="af7caa976fc5766ddc3d89eef1965a9c6"></a>
<h2 class="memtitle"><span class="permalink"><a href="#af7caa976fc5766ddc3d89eef1965a9c6">&#9670;&nbsp;</a></span>mousePressEvent()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void WindowButton::mousePressEvent </td>
          <td>(</td>
          <td class="paramtype">QMouseEvent *&#160;</td>
          <td class="paramname"><em>event</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>The mouse press event of the button. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">event</td><td>The event to treat </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

</div>
</div>
<a id="afd414539e6cf2fc7072a175032a6f1ff"></a>
<h2 class="memtitle"><span class="permalink"><a href="#afd414539e6cf2fc7072a175032a6f1ff">&#9670;&nbsp;</a></span>mouseReleaseEvent()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void WindowButton::mouseReleaseEvent </td>
          <td>(</td>
          <td class="paramtype">QMouseEvent *&#160;</td>
          <td class="paramname"><em>event</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>The mouse release event of the button. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">event</td><td>The event to treat </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

</div>
</div>
<a id="a9d63cf19bcf3f8ba8a7f03fe4f222f11"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a9d63cf19bcf3f8ba8a7f03fe4f222f11">&#9670;&nbsp;</a></span>paintEvent()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void WindowButton::paintEvent </td>
          <td>(</td>
          <td class="paramtype">QPaintEvent *&#160;</td>
          <td class="paramname"><em>event</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>The paint event of the button. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">event</td><td>The event to treat </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

</div>
</div>
<a id="a2dd52661908250a571804fe967bcd316"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a2dd52661908250a571804fe967bcd316">&#9670;&nbsp;</a></span>resizeEvent()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void WindowButton::resizeEvent </td>
          <td>(</td>
          <td class="paramtype">QResizeEvent *&#160;</td>
          <td class="paramname"><em>event</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>The resize event of the button. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">event</td><td>The event to treat </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

</div>
</div>
<a id="ac7b9d8d3e328e0285ef4664e20acb8d3"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ac7b9d8d3e328e0285ef4664e20acb8d3">&#9670;&nbsp;</a></span>setBackground()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void WindowButton::setBackground </td>
          <td>(</td>
          <td class="paramtype">int&#160;</td>
          <td class="paramname"><em>r</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">int&#160;</td>
          <td class="paramname"><em>g</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">int&#160;</td>
          <td class="paramname"><em>b</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">int&#160;</td>
          <td class="paramname"><em>a</em> = <code>255</code>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Set the background color of the button. </p>

</div>
</div>
<a id="a7a087338372f7592853b050d168df152"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a7a087338372f7592853b050d168df152">&#9670;&nbsp;</a></span>setClickedColor()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void WindowButton::setClickedColor </td>
          <td>(</td>
          <td class="paramtype">int&#160;</td>
          <td class="paramname"><em>r</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">int&#160;</td>
          <td class="paramname"><em>g</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">int&#160;</td>
          <td class="paramname"><em>b</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">int&#160;</td>
          <td class="paramname"><em>a</em> = <code>255</code>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Set the clicked color of the button lines. </p>

</div>
</div>
<a id="a434a8192bfe4dea8c7b4e1b052a1a943"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a434a8192bfe4dea8c7b4e1b052a1a943">&#9670;&nbsp;</a></span>setGradient()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void WindowButton::setGradient </td>
          <td>(</td>
          <td class="paramtype">int&#160;</td>
          <td class="paramname"><em>r1</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">int&#160;</td>
          <td class="paramname"><em>g1</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">int&#160;</td>
          <td class="paramname"><em>b1</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">int&#160;</td>
          <td class="paramname"><em>a1</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">int&#160;</td>
          <td class="paramname"><em>r2</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">int&#160;</td>
          <td class="paramname"><em>g2</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">int&#160;</td>
          <td class="paramname"><em>b2</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">int&#160;</td>
          <td class="paramname"><em>a2</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Set the gradient background color of the button. </p>

</div>
</div>
<a id="a6947ea55943b909c1d492ad2f79ae1f8"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a6947ea55943b909c1d492ad2f79ae1f8">&#9670;&nbsp;</a></span>setHoveredColor()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void WindowButton::setHoveredColor </td>
          <td>(</td>
          <td class="paramtype">int&#160;</td>
          <td class="paramname"><em>r</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">int&#160;</td>
          <td class="paramname"><em>g</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">int&#160;</td>
          <td class="paramname"><em>b</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">int&#160;</td>
          <td class="paramname"><em>a</em> = <code>255</code>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Set the hovered color of the button lines. </p>

</div>
</div>
<a id="a4babac31336534efca737c5f73710c1d"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a4babac31336534efca737c5f73710c1d">&#9670;&nbsp;</a></span>setNormalColor()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void WindowButton::setNormalColor </td>
          <td>(</td>
          <td class="paramtype">int&#160;</td>
          <td class="paramname"><em>r</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">int&#160;</td>
          <td class="paramname"><em>g</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">int&#160;</td>
          <td class="paramname"><em>b</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">int&#160;</td>
          <td class="paramname"><em>a</em> = <code>255</code>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Set the normal color of the button lines. </p>

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li><a class="el" href="../../dd/d32/a00041_source.php">WindowButton.hpp</a></li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="../../d5/d1e/a00103.php">WindowButton</a></li>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.13 </li>
  </ul>
</div>
</body>
</html>
