<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.13"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>Qt: Member List</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Qt
   &#160;<span id="projectnumber">1.0</span>
   </div>
   <div id="projectbrief">Specific widgets for Qt</div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d3/d8b/a00059.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="headertitle">
<div class="title">GraphScene Member List</div>  </div>
</div><!--header-->
<div class="contents">

<p>This is the complete list of members for <a class="el" href="../../d3/d8b/a00059.php">GraphScene</a>, including all inherited members.</p>
<table class="directory">
  <tr class="even"><td class="entry"><a class="el" href="../../d3/d8b/a00059.php#ad24a3692edd1ba8099c9b823ca91705c">addGraph</a>(std::map&lt; T, T &gt; ins)</td><td class="entry"><a class="el" href="../../d3/d8b/a00059.php">GraphScene</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d3/d8b/a00059.php#aa00a275c68b5ba1fd39998c2e47db34a">addGraph</a>(std::pair&lt; T, T &gt; in)</td><td class="entry"><a class="el" href="../../d3/d8b/a00059.php">GraphScene</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d3/d8b/a00059.php#a0ae96172f1b8598300c4ac6134444697">addGraph</a>(std::vector&lt; T &gt; ins)</td><td class="entry"><a class="el" href="../../d3/d8b/a00059.php">GraphScene</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d3/d8b/a00059.php#a262f69fe1830ded7878cf087236024f0">addInGraph</a>(size_t index, std::pair&lt; T, T &gt; vals)</td><td class="entry"><a class="el" href="../../d3/d8b/a00059.php">GraphScene</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d3/d8b/a00059.php#a14cdb7c7d2167512a42815286cd75dba">getNbGraphs</a>()</td><td class="entry"><a class="el" href="../../d3/d8b/a00059.php">GraphScene</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d3/d8b/a00059.php#a7c64f302d928e583cecd5602f3ef9b6e">GraphScene</a>(QObject *parent=nullptr)</td><td class="entry"><a class="el" href="../../d3/d8b/a00059.php">GraphScene</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d9/da5/a00075.php#a5b9c0375ba50d6f3f7e83d983088ac08">initialized</a></td><td class="entry"><a class="el" href="../../d9/da5/a00075.php">Scene</a></td><td class="entry"><span class="mlabel">protected</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d3/d8b/a00059.php#a9ee91facfb6fd4eda61385809e122f43">reinit</a>()</td><td class="entry"><a class="el" href="../../d3/d8b/a00059.php">GraphScene</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d9/da5/a00075.php#abaaf58cde185094df3ab47c5eedef55e">Scene</a>(QObject *parent=nullptr)</td><td class="entry"><a class="el" href="../../d9/da5/a00075.php">Scene</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="../../d3/d8b/a00059.php#a8039208138c6c15d89f3460b552f6b37">setPointsDist</a>(T dist)</td><td class="entry"><a class="el" href="../../d3/d8b/a00059.php">GraphScene</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d3/d8b/a00059.php#a294013125013fbd6218eeb892c53d6b4">setXMax</a>(T in)</td><td class="entry"><a class="el" href="../../d3/d8b/a00059.php">GraphScene</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d3/d8b/a00059.php#a53a17a634417fcde5b9cac44699ed7a6">setXMin</a>(T in)</td><td class="entry"><a class="el" href="../../d3/d8b/a00059.php">GraphScene</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d3/d8b/a00059.php#a7b4d85fc0786904021c33902cec3dbdb">setXRange</a>(T min, T max)</td><td class="entry"><a class="el" href="../../d3/d8b/a00059.php">GraphScene</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d3/d8b/a00059.php#a7bcd5ff38039ca92991a9b72b6f0e8ea">setXStep</a>(T in)</td><td class="entry"><a class="el" href="../../d3/d8b/a00059.php">GraphScene</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d3/d8b/a00059.php#a4345f99a23e4cc5fa07c55cf3511537e">setYMax</a>(T in)</td><td class="entry"><a class="el" href="../../d3/d8b/a00059.php">GraphScene</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d3/d8b/a00059.php#a4a87303127505bce46d4dcc30ce1f122">setYMin</a>(T in)</td><td class="entry"><a class="el" href="../../d3/d8b/a00059.php">GraphScene</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d3/d8b/a00059.php#a4f75f2238bcc5df131f3e4198bc1c186">setYRange</a>(T min, T max)</td><td class="entry"><a class="el" href="../../d3/d8b/a00059.php">GraphScene</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d3/d8b/a00059.php#a0691b268ad07ea33bf254b0f489df59d">setYStep</a>(T in)</td><td class="entry"><a class="el" href="../../d3/d8b/a00059.php">GraphScene</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d3/d8b/a00059.php#ae19cfdde3c7cb4f1a1bbddc689b6c5b5">update</a>()</td><td class="entry"><a class="el" href="../../d3/d8b/a00059.php">GraphScene</a></td><td class="entry"><span class="mlabel">slot</span></td></tr>
  <tr><td class="entry"><a class="el" href="../../d3/d8b/a00059.php#a37cbb072493b457564dda12502c9af7f">~GraphScene</a>()</td><td class="entry"><a class="el" href="../../d3/d8b/a00059.php">GraphScene</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="../../d9/da5/a00075.php#a3b8cec2e32546713915f8c6303c951f1">~Scene</a>()</td><td class="entry"><a class="el" href="../../d9/da5/a00075.php">Scene</a></td><td class="entry"></td></tr>
</table></div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.13 </li>
  </ul>
</div>
</body>
</html>
