<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.13"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>Qt: DrawScene Class Reference</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Qt
   &#160;<span id="projectnumber">1.0</span>
   </div>
   <div id="projectbrief">Specific widgets for Qt</div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d2/d79/a00051.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#pub-slots">Public Slots</a> &#124;
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pro-attribs">Protected Attributes</a> &#124;
<a href="../../d4/dca/a00048.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">DrawScene Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>A <a class="el" href="../../d9/da5/a00075.php" title="An implementation of QGraphcsScene with an updator. ">Scene</a> implementation to draw with tiles system.  
 <a href="../../d2/d79/a00051.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="../../d7/d46/a00002_source.php">DrawScene.hpp</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for DrawScene:</div>
<div class="dyncontent">
<div class="center"><img src="../../d5/de0/a00050.png" border="0" usemap="#DrawScene_inherit__map" alt="Inheritance graph"/></div>
<map name="DrawScene_inherit__map" id="DrawScene_inherit__map">
<area shape="rect" id="node2" href="../../d9/da5/a00075.php" title="An implementation of QGraphcsScene with an updator. " alt="" coords="37,80,95,107"/>
</map>
<center><span class="legend">[<a target="top" href="../../graph_legend.php">legend</a>]</span></center></div>
<div class="dynheader">
Collaboration diagram for DrawScene:</div>
<div class="dyncontent">
<div class="center"><img src="../../d2/dee/a00049.png" border="0" usemap="#DrawScene_coll__map" alt="Collaboration graph"/></div>
<map name="DrawScene_coll__map" id="DrawScene_coll__map">
<area shape="rect" id="node2" href="../../d9/da5/a00075.php" title="An implementation of QGraphcsScene with an updator. " alt="" coords="37,80,95,107"/>
</map>
<center><span class="legend">[<a target="top" href="../../graph_legend.php">legend</a>]</span></center></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-slots"></a>
Public Slots</h2></td></tr>
<tr class="memitem:ad0292ea7a4d4c501a7bf5c9fb6282d7e"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d2/d79/a00051.php#ad0292ea7a4d4c501a7bf5c9fb6282d7e">update</a> ()</td></tr>
<tr class="memdesc:ad0292ea7a4d4c501a7bf5c9fb6282d7e"><td class="mdescLeft">&#160;</td><td class="mdescRight">Overload of the pur virtual parent method <a class="el" href="../../d9/da5/a00075.php#a7faff47f5c1b1ebc986f768c9b9732ec" title="A pure virtual method to redefine it in child classes. ">Scene::update()</a>  <a href="#ad0292ea7a4d4c501a7bf5c9fb6282d7e">More...</a><br /></td></tr>
<tr class="separator:ad0292ea7a4d4c501a7bf5c9fb6282d7e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pub_slots_a00075"><td colspan="2" onclick="javascript:toggleInherit('pub_slots_a00075')"><img src="../../closed.png" alt="-"/>&#160;Public Slots inherited from <a class="el" href="../../d9/da5/a00075.php">Scene</a></td></tr>
<tr class="memitem:a7faff47f5c1b1ebc986f768c9b9732ec inherit pub_slots_a00075"><td class="memItemLeft" align="right" valign="top">virtual void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d9/da5/a00075.php#a7faff47f5c1b1ebc986f768c9b9732ec">update</a> ()=0</td></tr>
<tr class="memdesc:a7faff47f5c1b1ebc986f768c9b9732ec inherit pub_slots_a00075"><td class="mdescLeft">&#160;</td><td class="mdescRight">A pure virtual method to redefine it in child classes.  <a href="../../d9/da5/a00075.php#a7faff47f5c1b1ebc986f768c9b9732ec">More...</a><br /></td></tr>
<tr class="separator:a7faff47f5c1b1ebc986f768c9b9732ec inherit pub_slots_a00075"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a8264ece5e7fb59ec874720b710d8f353"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d2/d79/a00051.php#a8264ece5e7fb59ec874720b710d8f353">DrawScene</a> (QObject *parent=nullptr)</td></tr>
<tr class="memdesc:a8264ece5e7fb59ec874720b710d8f353"><td class="mdescLeft">&#160;</td><td class="mdescRight">Create the <a class="el" href="../../d2/d79/a00051.php" title="A Scene implementation to draw with tiles system. ">DrawScene</a>.  <a href="#a8264ece5e7fb59ec874720b710d8f353">More...</a><br /></td></tr>
<tr class="separator:a8264ece5e7fb59ec874720b710d8f353"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab95069018a89de490bb75a7847a7c999"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d2/d79/a00051.php#ab95069018a89de490bb75a7847a7c999">~DrawScene</a> ()</td></tr>
<tr class="separator:ab95069018a89de490bb75a7847a7c999"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa9cd414cc46f3396f58e4a7af88d6b4c"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d2/d79/a00051.php#aa9cd414cc46f3396f58e4a7af88d6b4c">setTilesize</a> (int s)</td></tr>
<tr class="memdesc:aa9cd414cc46f3396f58e4a7af88d6b4c"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the tiles' size.  <a href="#aa9cd414cc46f3396f58e4a7af88d6b4c">More...</a><br /></td></tr>
<tr class="separator:aa9cd414cc46f3396f58e4a7af88d6b4c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pub_methods_a00075"><td colspan="2" onclick="javascript:toggleInherit('pub_methods_a00075')"><img src="../../closed.png" alt="-"/>&#160;Public Member Functions inherited from <a class="el" href="../../d9/da5/a00075.php">Scene</a></td></tr>
<tr class="memitem:abaaf58cde185094df3ab47c5eedef55e inherit pub_methods_a00075"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d9/da5/a00075.php#abaaf58cde185094df3ab47c5eedef55e">Scene</a> (QObject *parent=nullptr)</td></tr>
<tr class="memdesc:abaaf58cde185094df3ab47c5eedef55e inherit pub_methods_a00075"><td class="mdescLeft">&#160;</td><td class="mdescRight">Construct the QGraphicsScene.  <a href="../../d9/da5/a00075.php#abaaf58cde185094df3ab47c5eedef55e">More...</a><br /></td></tr>
<tr class="separator:abaaf58cde185094df3ab47c5eedef55e inherit pub_methods_a00075"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3b8cec2e32546713915f8c6303c951f1 inherit pub_methods_a00075"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d9/da5/a00075.php#a3b8cec2e32546713915f8c6303c951f1">~Scene</a> ()</td></tr>
<tr class="separator:a3b8cec2e32546713915f8c6303c951f1 inherit pub_methods_a00075"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pro-attribs"></a>
Protected Attributes</h2></td></tr>
<tr class="memitem:a124d4bd03677251c2159bd0dd4254306"><td class="memItemLeft" align="right" valign="top">int&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d2/d79/a00051.php#a124d4bd03677251c2159bd0dd4254306">tileSize</a></td></tr>
<tr class="separator:a124d4bd03677251c2159bd0dd4254306"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aecb82ecbd590818d52d58227101a490d"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d2/d79/a00051.php#aecb82ecbd590818d52d58227101a490d">printed_background</a></td></tr>
<tr class="separator:aecb82ecbd590818d52d58227101a490d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a99f3c0b81bbecfbf850e920ffc2f6f0a"><td class="memItemLeft" align="right" valign="top">std::map&lt; std::string, QPixmap &gt;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d2/d79/a00051.php#a99f3c0b81bbecfbf850e920ffc2f6f0a">pixmaps</a></td></tr>
<tr class="separator:a99f3c0b81bbecfbf850e920ffc2f6f0a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af1a71ac1ae84ae88e00810307b2f146d"><td class="memItemLeft" align="right" valign="top">std::map&lt; std::string, QPixmap &gt;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d2/d79/a00051.php#af1a71ac1ae84ae88e00810307b2f146d">scaled_pixmaps</a></td></tr>
<tr class="separator:af1a71ac1ae84ae88e00810307b2f146d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pro_attribs_a00075"><td colspan="2" onclick="javascript:toggleInherit('pro_attribs_a00075')"><img src="../../closed.png" alt="-"/>&#160;Protected Attributes inherited from <a class="el" href="../../d9/da5/a00075.php">Scene</a></td></tr>
<tr class="memitem:a5b9c0375ba50d6f3f7e83d983088ac08 inherit pro_attribs_a00075"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d9/da5/a00075.php#a5b9c0375ba50d6f3f7e83d983088ac08">initialized</a></td></tr>
<tr class="separator:a5b9c0375ba50d6f3f7e83d983088ac08 inherit pro_attribs_a00075"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>A <a class="el" href="../../d9/da5/a00075.php" title="An implementation of QGraphcsScene with an updator. ">Scene</a> implementation to draw with tiles system. </p>

<p class="definition">Definition at line <a class="el" href="../../d7/d46/a00002_source.php#l00017">17</a> of file <a class="el" href="../../d7/d46/a00002_source.php">DrawScene.hpp</a>.</p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a id="a8264ece5e7fb59ec874720b710d8f353"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a8264ece5e7fb59ec874720b710d8f353">&#9670;&nbsp;</a></span>DrawScene()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">DrawScene::DrawScene </td>
          <td>(</td>
          <td class="paramtype">QObject *&#160;</td>
          <td class="paramname"><em>parent</em> = <code>nullptr</code></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Create the <a class="el" href="../../d2/d79/a00051.php" title="A Scene implementation to draw with tiles system. ">DrawScene</a>. </p>

</div>
</div>
<a id="ab95069018a89de490bb75a7847a7c999"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ab95069018a89de490bb75a7847a7c999">&#9670;&nbsp;</a></span>~DrawScene()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">DrawScene::~DrawScene </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a id="aa9cd414cc46f3396f58e4a7af88d6b4c"></a>
<h2 class="memtitle"><span class="permalink"><a href="#aa9cd414cc46f3396f58e4a7af88d6b4c">&#9670;&nbsp;</a></span>setTilesize()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void DrawScene::setTilesize </td>
          <td>(</td>
          <td class="paramtype">int&#160;</td>
          <td class="paramname"><em>s</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Set the tiles' size. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">s</td><td>The value to set</td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

</div>
</div>
<a id="ad0292ea7a4d4c501a7bf5c9fb6282d7e"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ad0292ea7a4d4c501a7bf5c9fb6282d7e">&#9670;&nbsp;</a></span>update</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void DrawScene::update </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">slot</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Overload of the pur virtual parent method <a class="el" href="../../d9/da5/a00075.php#a7faff47f5c1b1ebc986f768c9b9732ec" title="A pure virtual method to redefine it in child classes. ">Scene::update()</a> </p>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

</div>
</div>
<h2 class="groupheader">Member Data Documentation</h2>
<a id="a99f3c0b81bbecfbf850e920ffc2f6f0a"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a99f3c0b81bbecfbf850e920ffc2f6f0a">&#9670;&nbsp;</a></span>pixmaps</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">std::map&lt;std::string, QPixmap&gt; DrawScene::pixmaps</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p class="definition">Definition at line <a class="el" href="../../d7/d46/a00002_source.php#l00046">46</a> of file <a class="el" href="../../d7/d46/a00002_source.php">DrawScene.hpp</a>.</p>

</div>
</div>
<a id="aecb82ecbd590818d52d58227101a490d"></a>
<h2 class="memtitle"><span class="permalink"><a href="#aecb82ecbd590818d52d58227101a490d">&#9670;&nbsp;</a></span>printed_background</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">bool DrawScene::printed_background</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p class="definition">Definition at line <a class="el" href="../../d7/d46/a00002_source.php#l00044">44</a> of file <a class="el" href="../../d7/d46/a00002_source.php">DrawScene.hpp</a>.</p>

</div>
</div>
<a id="af1a71ac1ae84ae88e00810307b2f146d"></a>
<h2 class="memtitle"><span class="permalink"><a href="#af1a71ac1ae84ae88e00810307b2f146d">&#9670;&nbsp;</a></span>scaled_pixmaps</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">std::map&lt;std::string, QPixmap&gt; DrawScene::scaled_pixmaps</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p class="definition">Definition at line <a class="el" href="../../d7/d46/a00002_source.php#l00047">47</a> of file <a class="el" href="../../d7/d46/a00002_source.php">DrawScene.hpp</a>.</p>

</div>
</div>
<a id="a124d4bd03677251c2159bd0dd4254306"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a124d4bd03677251c2159bd0dd4254306">&#9670;&nbsp;</a></span>tileSize</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">int DrawScene::tileSize</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p class="definition">Definition at line <a class="el" href="../../d7/d46/a00002_source.php#l00043">43</a> of file <a class="el" href="../../d7/d46/a00002_source.php">DrawScene.hpp</a>.</p>

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li><a class="el" href="../../d7/d46/a00002_source.php">DrawScene.hpp</a></li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="../../d2/d79/a00051.php">DrawScene</a></li>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.13 </li>
  </ul>
</div>
</body>
</html>
