<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.13"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>Qt: Window.hpp Source File</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Qt
   &#160;<span id="projectnumber">1.0</span>
   </div>
   <div id="projectbrief">Specific widgets for Qt</div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d8/d41/a00038_source.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="headertitle">
<div class="title">Window.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="../../d8/d41/a00038.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00006"></a><span class="lineno">    6</span>&#160;<span class="preprocessor">#ifndef HEADER_WINDOW</span></div><div class="line"><a name="l00007"></a><span class="lineno">    7</span>&#160;<span class="preprocessor">#define HEADER_WINDOW</span></div><div class="line"><a name="l00008"></a><span class="lineno">    8</span>&#160;</div><div class="line"><a name="l00009"></a><span class="lineno">    9</span>&#160;<span class="preprocessor">#ifdef Q_WS_X11</span></div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;<span class="preprocessor">    #include &lt;QX11Info&gt;</span></div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;<span class="preprocessor">#endif</span></div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;</div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;<span class="preprocessor">#include &lt;QtWidgets&gt;</span></div><div class="line"><a name="l00014"></a><span class="lineno">   14</span>&#160;</div><div class="line"><a name="l00015"></a><span class="lineno">   15</span>&#160;<span class="preprocessor">#include &quot;<a class="code" href="../../d5/df9/a00044.php">WindowTitleBar.hpp</a>&quot;</span></div><div class="line"><a name="l00016"></a><span class="lineno">   16</span>&#160;<span class="preprocessor">#include &quot;C++/C++.hpp&quot;</span></div><div class="line"><a name="l00017"></a><span class="lineno">   17</span>&#160;</div><div class="line"><a name="l00022"></a><span class="lineno"><a class="line" href="../../da/d74/a00099.php">   22</a></span>&#160;<span class="keyword">class </span><a class="code" href="../../da/d74/a00099.php">Window</a> : <span class="keyword">public</span> <a class="code" href="../../d9/d77/a00095.php">Widget</a> {</div><div class="line"><a name="l00023"></a><span class="lineno">   23</span>&#160;    Q_OBJECT</div><div class="line"><a name="l00024"></a><span class="lineno">   24</span>&#160;    <span class="keyword">public</span>:</div><div class="line"><a name="l00029"></a><span class="lineno">   29</span>&#160;        <a class="code" href="../../da/d74/a00099.php#a8c86e48ef3180201cc97cb928abd66ca">Window</a>(QWidget* parent = <span class="keyword">nullptr</span>);</div><div class="line"><a name="l00031"></a><span class="lineno">   31</span>&#160;        <a class="code" href="../../da/d74/a00099.php#a245d821e6016fa1f6970ccbbedd635f6">~Window</a>();</div><div class="line"><a name="l00032"></a><span class="lineno">   32</span>&#160;</div><div class="line"><a name="l00038"></a><span class="lineno">   38</span>&#160;        <span class="keywordtype">void</span> <a class="code" href="../../da/d74/a00099.php#a008e887882941bcd08b6439dc001ea51">setWindowTitle</a>(<span class="keyword">const</span> QString &amp;title);</div><div class="line"><a name="l00044"></a><span class="lineno">   44</span>&#160;        <span class="keywordtype">void</span> <a class="code" href="../../da/d74/a00099.php#a8c65cb42e811de87be8743af6b9d21ed">setCentralWidget</a>(QWidget* widget);</div><div class="line"><a name="l00051"></a><span class="lineno">   51</span>&#160;        <span class="keywordtype">void</span> <a class="code" href="../../da/d74/a00099.php#a2983759dc6be4f8da44eff6069b2d3c8">setSize</a>(<span class="keywordtype">int</span> w, <span class="keywordtype">int</span> h);</div><div class="line"><a name="l00052"></a><span class="lineno">   52</span>&#160;</div><div class="line"><a name="l00058"></a><span class="lineno"><a class="line" href="../../da/d74/a00099.php#a4cec8e761a776437c9886d6982c22a54">   58</a></span>&#160;        <span class="keywordtype">void</span> <a class="code" href="../../da/d74/a00099.php#a4cec8e761a776437c9886d6982c22a54">setMargin</a>(<span class="keywordtype">int</span> m){ this-&gt;<a class="code" href="../../da/d74/a00099.php#a4cec8e761a776437c9886d6982c22a54">setMargin</a>(m, m, m, m); }</div><div class="line"><a name="l00067"></a><span class="lineno">   67</span>&#160;        <span class="keywordtype">void</span> <a class="code" href="../../da/d74/a00099.php#a4cec8e761a776437c9886d6982c22a54">setMargin</a>(<span class="keywordtype">int</span> t, <span class="keywordtype">int</span> r, <span class="keywordtype">int</span> b, <span class="keywordtype">int</span> l);</div><div class="line"><a name="l00068"></a><span class="lineno">   68</span>&#160;</div><div class="line"><a name="l00073"></a><span class="lineno">   73</span>&#160;        <span class="keywordtype">void</span> <a class="code" href="../../da/d74/a00099.php#a673240610da13a2424d4a7591fb19026">fullscreen</a>();</div><div class="line"><a name="l00078"></a><span class="lineno">   78</span>&#160;        <span class="keywordtype">void</span> <a class="code" href="../../da/d74/a00099.php#a97078387be519b16401c3bb0f299aa01">minimize</a>();</div><div class="line"><a name="l00083"></a><span class="lineno">   83</span>&#160;        <span class="keywordtype">void</span> <a class="code" href="../../da/d74/a00099.php#ad21ca1bd9a5c01411800f931bd7b1f7d">quit</a>();</div><div class="line"><a name="l00084"></a><span class="lineno">   84</span>&#160;</div><div class="line"><a name="l00085"></a><span class="lineno">   85</span>&#160;    <span class="keyword">protected</span>:</div><div class="line"><a name="l00091"></a><span class="lineno">   91</span>&#160;        <span class="keywordtype">void</span> <a class="code" href="../../da/d74/a00099.php#a677a2c1046a84743e709515f5618b1e8">showEvent</a>(QShowEvent* event);</div><div class="line"><a name="l00097"></a><span class="lineno">   97</span>&#160;        <span class="keywordtype">void</span> <a class="code" href="../../da/d74/a00099.php#a1b653d42eb4810a8c0be48dc65d98b3a">paintEvent</a>(QPaintEvent* event);</div><div class="line"><a name="l00103"></a><span class="lineno">  103</span>&#160;        <span class="keywordtype">void</span> <a class="code" href="../../da/d74/a00099.php#a3d72edbec3fed3709ea3d374973c70b4">resizeEvent</a>(QResizeEvent* event);</div><div class="line"><a name="l00104"></a><span class="lineno">  104</span>&#160;</div><div class="line"><a name="l00112"></a><span class="lineno">  112</span>&#160;        <span class="keyword">virtual</span> <span class="keywordtype">void</span> <a class="code" href="../../da/d74/a00099.php#a1ce5696d3fac4e90e6c9fbd0477d0f9d">drawBackground</a>(QPixmap* cache);</div><div class="line"><a name="l00118"></a><span class="lineno">  118</span>&#160;        <span class="keywordtype">void</span> <a class="code" href="../../da/d74/a00099.php#acbed45e30a51c6855e5e6ea88197b161">drawDefaultBackground</a>(QPixmap* cache);</div><div class="line"><a name="l00124"></a><span class="lineno">  124</span>&#160;        <span class="keywordtype">void</span> <a class="code" href="../../da/d74/a00099.php#a3f710c0adafe15f27766f70a1c5b4dee">setBackground</a>(QPixmap* cache = <span class="keyword">nullptr</span>);</div><div class="line"><a name="l00125"></a><span class="lineno">  125</span>&#160;</div><div class="line"><a name="l00131"></a><span class="lineno">  131</span>&#160;        <span class="keywordtype">void</span> <a class="code" href="../../da/d74/a00099.php#a85b13ae29ce6f9aa9ffb7408b0ddd4b7">enableResize</a>(<span class="keywordtype">bool</span> enable);</div><div class="line"><a name="l00137"></a><span class="lineno">  137</span>&#160;        <span class="keywordtype">void</span> <a class="code" href="../../da/d74/a00099.php#a8ad2a767e19299b153f9bc0457f13114">showTitlebar</a>(<span class="keywordtype">bool</span> enable);</div><div class="line"><a name="l00138"></a><span class="lineno">  138</span>&#160;</div><div class="line"><a name="l00139"></a><span class="lineno">  139</span>&#160;    signals:</div><div class="line"><a name="l00145"></a><span class="lineno">  145</span>&#160;        <span class="keywordtype">void</span> <a class="code" href="../../da/d74/a00099.php#a56ced9e90dad8415ce9ba9ccdb8f50c7">WindowTitleChanged</a>(QString title);</div><div class="line"><a name="l00151"></a><span class="lineno">  151</span>&#160;        <span class="keywordtype">void</span> <a class="code" href="../../da/d74/a00099.php#a9b8e592bf73f07ec549125eb6367395c">WindowResizeChanged</a>(<span class="keywordtype">bool</span> state);</div><div class="line"><a name="l00157"></a><span class="lineno">  157</span>&#160;        <span class="keywordtype">void</span> <a class="code" href="../../da/d74/a00099.php#a1f3319d59097b7c9e5bde545e6867c1b">TitleBarShowState</a>(<span class="keywordtype">bool</span> state);</div><div class="line"><a name="l00158"></a><span class="lineno">  158</span>&#160;</div><div class="line"><a name="l00163"></a><span class="lineno">  163</span>&#160;        <span class="keywordtype">void</span> <a class="code" href="../../da/d74/a00099.php#a801605000f4773291ab5b5e07c6155bc">Fullscreen</a>();</div><div class="line"><a name="l00168"></a><span class="lineno">  168</span>&#160;        <span class="keywordtype">void</span> <a class="code" href="../../da/d74/a00099.php#a16563366618e73bee12d9cd5358c57ea">Reduice</a>();</div><div class="line"><a name="l00173"></a><span class="lineno">  173</span>&#160;        <span class="keywordtype">void</span> <a class="code" href="../../da/d74/a00099.php#a57d28573876dd89be70cd78b9302f461">Quit</a>();</div><div class="line"><a name="l00174"></a><span class="lineno">  174</span>&#160;</div><div class="line"><a name="l00175"></a><span class="lineno">  175</span>&#160;    <span class="keyword">private</span>:</div><div class="line"><a name="l00177"></a><span class="lineno">  177</span>&#160;        <span class="keywordtype">void</span> CenterOnScreen();</div><div class="line"><a name="l00178"></a><span class="lineno">  178</span>&#160;</div><div class="line"><a name="l00180"></a><span class="lineno">  180</span>&#160;        <span class="keywordtype">void</span> setTransparency();</div><div class="line"><a name="l00182"></a><span class="lineno">  182</span>&#160;        <span class="keywordtype">void</span> useTransparency();</div><div class="line"><a name="l00183"></a><span class="lineno">  183</span>&#160;</div><div class="line"><a name="l00184"></a><span class="lineno">  184</span>&#160;    <span class="keyword">protected</span>:</div><div class="line"><a name="l00185"></a><span class="lineno"><a class="line" href="../../da/d74/a00099.php#a065e43061d8abb3717302dc1acf139c3">  185</a></span>&#160;        QPixmap* <a class="code" href="../../da/d74/a00099.php#a065e43061d8abb3717302dc1acf139c3">m_Cache</a>;</div><div class="line"><a name="l00186"></a><span class="lineno">  186</span>&#160;</div><div class="line"><a name="l00187"></a><span class="lineno">  187</span>&#160;    <span class="keyword">private</span>:</div><div class="line"><a name="l00188"></a><span class="lineno">  188</span>&#160;        QGridLayout* m_MainLayout;</div><div class="line"><a name="l00189"></a><span class="lineno">  189</span>&#160;        <a class="code" href="../../df/d98/a00107.php">WindowTitleBar</a>* m_TitleBar;</div><div class="line"><a name="l00190"></a><span class="lineno">  190</span>&#160;        QSizeGrip* m_SizeGrip;</div><div class="line"><a name="l00191"></a><span class="lineno">  191</span>&#160;</div><div class="line"><a name="l00192"></a><span class="lineno">  192</span>&#160;        QVBoxLayout* m_CenterLayout;</div><div class="line"><a name="l00193"></a><span class="lineno">  193</span>&#160;        QWidget* m_CenterWidget;</div><div class="line"><a name="l00194"></a><span class="lineno">  194</span>&#160;</div><div class="line"><a name="l00195"></a><span class="lineno">  195</span>&#160;        <span class="keywordtype">bool</span> transparent;</div><div class="line"><a name="l00196"></a><span class="lineno">  196</span>&#160;        <span class="keywordtype">bool</span> enabledResize;</div><div class="line"><a name="l00197"></a><span class="lineno">  197</span>&#160;        <span class="keywordtype">bool</span> isFullscreen;</div><div class="line"><a name="l00198"></a><span class="lineno">  198</span>&#160;};</div><div class="line"><a name="l00199"></a><span class="lineno">  199</span>&#160;</div><div class="line"><a name="l00200"></a><span class="lineno">  200</span>&#160;<span class="preprocessor">#endif //HEADER_WINDOW</span></div><div class="ttc" id="a00099_php_a3d72edbec3fed3709ea3d374973c70b4"><div class="ttname"><a href="../../da/d74/a00099.php#a3d72edbec3fed3709ea3d374973c70b4">Window::resizeEvent</a></div><div class="ttdeci">void resizeEvent(QResizeEvent *event)</div><div class="ttdoc">The resize event of the window. </div></div>
<div class="ttc" id="a00099_php_acbed45e30a51c6855e5e6ea88197b161"><div class="ttname"><a href="../../da/d74/a00099.php#acbed45e30a51c6855e5e6ea88197b161">Window::drawDefaultBackground</a></div><div class="ttdeci">void drawDefaultBackground(QPixmap *cache)</div><div class="ttdoc">Draw the default background of the window. </div></div>
<div class="ttc" id="a00099_php_a2983759dc6be4f8da44eff6069b2d3c8"><div class="ttname"><a href="../../da/d74/a00099.php#a2983759dc6be4f8da44eff6069b2d3c8">Window::setSize</a></div><div class="ttdeci">void setSize(int w, int h)</div><div class="ttdoc">Set the window size. </div></div>
<div class="ttc" id="a00095_php"><div class="ttname"><a href="../../d9/d77/a00095.php">Widget</a></div><div class="ttdoc">Create a personnalized Widget. </div><div class="ttdef"><b>Definition:</b> <a href="../../d4/d8c/a00035_source.php#l00017">Widget.hpp:17</a></div></div>
<div class="ttc" id="a00099_php_a1b653d42eb4810a8c0be48dc65d98b3a"><div class="ttname"><a href="../../da/d74/a00099.php#a1b653d42eb4810a8c0be48dc65d98b3a">Window::paintEvent</a></div><div class="ttdeci">void paintEvent(QPaintEvent *event)</div><div class="ttdoc">The paint event of the window. </div></div>
<div class="ttc" id="a00099_php_a97078387be519b16401c3bb0f299aa01"><div class="ttname"><a href="../../da/d74/a00099.php#a97078387be519b16401c3bb0f299aa01">Window::minimize</a></div><div class="ttdeci">void minimize()</div><div class="ttdoc">Call to minimize the window. </div></div>
<div class="ttc" id="a00099_php_a801605000f4773291ab5b5e07c6155bc"><div class="ttname"><a href="../../da/d74/a00099.php#a801605000f4773291ab5b5e07c6155bc">Window::Fullscreen</a></div><div class="ttdeci">void Fullscreen()</div><div class="ttdoc">Call when the window as to be fullscreened or not. </div></div>
<div class="ttc" id="a00107_php"><div class="ttname"><a href="../../df/d98/a00107.php">WindowTitleBar</a></div><div class="ttdoc">The titlebar of the Window class. </div><div class="ttdef"><b>Definition:</b> <a href="../../d5/df9/a00044_source.php#l00018">WindowTitleBar.hpp:18</a></div></div>
<div class="ttc" id="a00099_php_a1ce5696d3fac4e90e6c9fbd0477d0f9d"><div class="ttname"><a href="../../da/d74/a00099.php#a1ce5696d3fac4e90e6c9fbd0477d0f9d">Window::drawBackground</a></div><div class="ttdeci">virtual void drawBackground(QPixmap *cache)</div><div class="ttdoc">Draw the background of the window. </div></div>
<div class="ttc" id="a00099_php_a065e43061d8abb3717302dc1acf139c3"><div class="ttname"><a href="../../da/d74/a00099.php#a065e43061d8abb3717302dc1acf139c3">Window::m_Cache</a></div><div class="ttdeci">QPixmap * m_Cache</div><div class="ttdef"><b>Definition:</b> <a href="../../d8/d41/a00038_source.php#l00185">Window.hpp:185</a></div></div>
<div class="ttc" id="a00099_php_a673240610da13a2424d4a7591fb19026"><div class="ttname"><a href="../../da/d74/a00099.php#a673240610da13a2424d4a7591fb19026">Window::fullscreen</a></div><div class="ttdeci">void fullscreen()</div><div class="ttdoc">Call to fullscreen or unfullscreen the window. </div></div>
<div class="ttc" id="a00099_php_a008e887882941bcd08b6439dc001ea51"><div class="ttname"><a href="../../da/d74/a00099.php#a008e887882941bcd08b6439dc001ea51">Window::setWindowTitle</a></div><div class="ttdeci">void setWindowTitle(const QString &amp;title)</div><div class="ttdoc">Set the window title. </div></div>
<div class="ttc" id="a00099_php_a8c86e48ef3180201cc97cb928abd66ca"><div class="ttname"><a href="../../da/d74/a00099.php#a8c86e48ef3180201cc97cb928abd66ca">Window::Window</a></div><div class="ttdeci">Window(QWidget *parent=nullptr)</div><div class="ttdoc">The constructor. </div></div>
<div class="ttc" id="a00099_php_a8c65cb42e811de87be8743af6b9d21ed"><div class="ttname"><a href="../../da/d74/a00099.php#a8c65cb42e811de87be8743af6b9d21ed">Window::setCentralWidget</a></div><div class="ttdeci">void setCentralWidget(QWidget *widget)</div><div class="ttdoc">Set the central widget. </div></div>
<div class="ttc" id="a00099_php_a245d821e6016fa1f6970ccbbedd635f6"><div class="ttname"><a href="../../da/d74/a00099.php#a245d821e6016fa1f6970ccbbedd635f6">Window::~Window</a></div><div class="ttdeci">~Window()</div><div class="ttdoc">The destructor. </div></div>
<div class="ttc" id="a00099_php_a677a2c1046a84743e709515f5618b1e8"><div class="ttname"><a href="../../da/d74/a00099.php#a677a2c1046a84743e709515f5618b1e8">Window::showEvent</a></div><div class="ttdeci">void showEvent(QShowEvent *event)</div><div class="ttdoc">The show event of the window. </div></div>
<div class="ttc" id="a00099_php_a57d28573876dd89be70cd78b9302f461"><div class="ttname"><a href="../../da/d74/a00099.php#a57d28573876dd89be70cd78b9302f461">Window::Quit</a></div><div class="ttdeci">void Quit()</div><div class="ttdoc">Call when the window has to be closed. </div></div>
<div class="ttc" id="a00099_php_a4cec8e761a776437c9886d6982c22a54"><div class="ttname"><a href="../../da/d74/a00099.php#a4cec8e761a776437c9886d6982c22a54">Window::setMargin</a></div><div class="ttdeci">void setMargin(int m)</div><div class="ttdoc">Set the window margin. </div><div class="ttdef"><b>Definition:</b> <a href="../../d8/d41/a00038_source.php#l00058">Window.hpp:58</a></div></div>
<div class="ttc" id="a00099_php_a9b8e592bf73f07ec549125eb6367395c"><div class="ttname"><a href="../../da/d74/a00099.php#a9b8e592bf73f07ec549125eb6367395c">Window::WindowResizeChanged</a></div><div class="ttdeci">void WindowResizeChanged(bool state)</div><div class="ttdoc">Call when the window is resized. </div></div>
<div class="ttc" id="a00099_php_a8ad2a767e19299b153f9bc0457f13114"><div class="ttname"><a href="../../da/d74/a00099.php#a8ad2a767e19299b153f9bc0457f13114">Window::showTitlebar</a></div><div class="ttdeci">void showTitlebar(bool enable)</div><div class="ttdoc">Set the titlebar visibility. </div></div>
<div class="ttc" id="a00099_php_a85b13ae29ce6f9aa9ffb7408b0ddd4b7"><div class="ttname"><a href="../../da/d74/a00099.php#a85b13ae29ce6f9aa9ffb7408b0ddd4b7">Window::enableResize</a></div><div class="ttdeci">void enableResize(bool enable)</div><div class="ttdoc">Set if yes or no the window can be resized. </div></div>
<div class="ttc" id="a00099_php_a1f3319d59097b7c9e5bde545e6867c1b"><div class="ttname"><a href="../../da/d74/a00099.php#a1f3319d59097b7c9e5bde545e6867c1b">Window::TitleBarShowState</a></div><div class="ttdeci">void TitleBarShowState(bool state)</div><div class="ttdoc">Call when the state of the titlebar is changed show/hide. </div></div>
<div class="ttc" id="a00044_php"><div class="ttname"><a href="../../d5/df9/a00044.php">WindowTitleBar.hpp</a></div></div>
<div class="ttc" id="a00099_php_a3f710c0adafe15f27766f70a1c5b4dee"><div class="ttname"><a href="../../da/d74/a00099.php#a3f710c0adafe15f27766f70a1c5b4dee">Window::setBackground</a></div><div class="ttdeci">void setBackground(QPixmap *cache=nullptr)</div><div class="ttdoc">Set the background window. </div></div>
<div class="ttc" id="a00099_php_ad21ca1bd9a5c01411800f931bd7b1f7d"><div class="ttname"><a href="../../da/d74/a00099.php#ad21ca1bd9a5c01411800f931bd7b1f7d">Window::quit</a></div><div class="ttdeci">void quit()</div><div class="ttdoc">Call to close the window. </div></div>
<div class="ttc" id="a00099_php_a56ced9e90dad8415ce9ba9ccdb8f50c7"><div class="ttname"><a href="../../da/d74/a00099.php#a56ced9e90dad8415ce9ba9ccdb8f50c7">Window::WindowTitleChanged</a></div><div class="ttdeci">void WindowTitleChanged(QString title)</div><div class="ttdoc">Call when the window title is changed. </div></div>
<div class="ttc" id="a00099_php"><div class="ttname"><a href="../../da/d74/a00099.php">Window</a></div><div class="ttdoc">A custom window. </div><div class="ttdef"><b>Definition:</b> <a href="../../d8/d41/a00038_source.php#l00022">Window.hpp:22</a></div></div>
<div class="ttc" id="a00099_php_a16563366618e73bee12d9cd5358c57ea"><div class="ttname"><a href="../../da/d74/a00099.php#a16563366618e73bee12d9cd5358c57ea">Window::Reduice</a></div><div class="ttdeci">void Reduice()</div><div class="ttdoc">Call when the window has to be reduice or not. </div></div>
</div><!-- fragment --></div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="../../dir_badfd550b617ce52cc73ed1c8c9513f6.php">Algo</a></li><li class="navelem"><a class="el" href="../../dir_a02ca41573efbfa5a2fd3c2b5453f5e3.php">QTTests</a></li><li class="navelem"><a class="el" href="../../dir_241af41b803d499a248aecae0c64f982.php">Widgets</a></li><li class="navelem"><a class="el" href="../../d8/d41/a00038.php">Window.hpp</a></li>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.13 </li>
  </ul>
</div>
</body>
</html>
