<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.13"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>Qt: Window Class Reference</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Qt
   &#160;<span id="projectnumber">1.0</span>
   </div>
   <div id="projectbrief">Specific widgets for Qt</div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('da/d74/a00099.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#signals">Signals</a> &#124;
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pro-methods">Protected Member Functions</a> &#124;
<a href="#pro-attribs">Protected Attributes</a> &#124;
<a href="../../d9/df8/a00096.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">Window Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>A custom window.  
 <a href="../../da/d74/a00099.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="../../d8/d41/a00038_source.php">Window.hpp</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for Window:</div>
<div class="dyncontent">
<div class="center"><img src="../../d1/d44/a00098.png" border="0" usemap="#Window_inherit__map" alt="Inheritance graph"/></div>
<map name="Window_inherit__map" id="Window_inherit__map">
<area shape="rect" id="node2" href="../../d9/d77/a00095.php" title="Create a personnalized Widget. " alt="" coords="11,80,73,107"/>
</map>
<center><span class="legend">[<a target="top" href="../../graph_legend.php">legend</a>]</span></center></div>
<div class="dynheader">
Collaboration diagram for Window:</div>
<div class="dyncontent">
<div class="center"><img src="../../d1/d84/a00097.png" border="0" usemap="#Window_coll__map" alt="Collaboration graph"/></div>
<map name="Window_coll__map" id="Window_coll__map">
<area shape="rect" id="node2" href="../../d9/d77/a00095.php" title="Create a personnalized Widget. " alt="" coords="11,80,73,107"/>
</map>
<center><span class="legend">[<a target="top" href="../../graph_legend.php">legend</a>]</span></center></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="signals"></a>
Signals</h2></td></tr>
<tr class="memitem:a56ced9e90dad8415ce9ba9ccdb8f50c7"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d74/a00099.php#a56ced9e90dad8415ce9ba9ccdb8f50c7">WindowTitleChanged</a> (QString title)</td></tr>
<tr class="memdesc:a56ced9e90dad8415ce9ba9ccdb8f50c7"><td class="mdescLeft">&#160;</td><td class="mdescRight">Call when the window title is changed.  <a href="#a56ced9e90dad8415ce9ba9ccdb8f50c7">More...</a><br /></td></tr>
<tr class="separator:a56ced9e90dad8415ce9ba9ccdb8f50c7"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9b8e592bf73f07ec549125eb6367395c"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d74/a00099.php#a9b8e592bf73f07ec549125eb6367395c">WindowResizeChanged</a> (bool state)</td></tr>
<tr class="memdesc:a9b8e592bf73f07ec549125eb6367395c"><td class="mdescLeft">&#160;</td><td class="mdescRight">Call when the window is resized.  <a href="#a9b8e592bf73f07ec549125eb6367395c">More...</a><br /></td></tr>
<tr class="separator:a9b8e592bf73f07ec549125eb6367395c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1f3319d59097b7c9e5bde545e6867c1b"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d74/a00099.php#a1f3319d59097b7c9e5bde545e6867c1b">TitleBarShowState</a> (bool state)</td></tr>
<tr class="memdesc:a1f3319d59097b7c9e5bde545e6867c1b"><td class="mdescLeft">&#160;</td><td class="mdescRight">Call when the state of the titlebar is changed show/hide.  <a href="#a1f3319d59097b7c9e5bde545e6867c1b">More...</a><br /></td></tr>
<tr class="separator:a1f3319d59097b7c9e5bde545e6867c1b"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a801605000f4773291ab5b5e07c6155bc"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d74/a00099.php#a801605000f4773291ab5b5e07c6155bc">Fullscreen</a> ()</td></tr>
<tr class="memdesc:a801605000f4773291ab5b5e07c6155bc"><td class="mdescLeft">&#160;</td><td class="mdescRight">Call when the window as to be fullscreened or not.  <a href="#a801605000f4773291ab5b5e07c6155bc">More...</a><br /></td></tr>
<tr class="separator:a801605000f4773291ab5b5e07c6155bc"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a16563366618e73bee12d9cd5358c57ea"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d74/a00099.php#a16563366618e73bee12d9cd5358c57ea">Reduice</a> ()</td></tr>
<tr class="memdesc:a16563366618e73bee12d9cd5358c57ea"><td class="mdescLeft">&#160;</td><td class="mdescRight">Call when the window has to be reduice or not.  <a href="#a16563366618e73bee12d9cd5358c57ea">More...</a><br /></td></tr>
<tr class="separator:a16563366618e73bee12d9cd5358c57ea"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a57d28573876dd89be70cd78b9302f461"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d74/a00099.php#a57d28573876dd89be70cd78b9302f461">Quit</a> ()</td></tr>
<tr class="memdesc:a57d28573876dd89be70cd78b9302f461"><td class="mdescLeft">&#160;</td><td class="mdescRight">Call when the window has to be closed.  <a href="#a57d28573876dd89be70cd78b9302f461">More...</a><br /></td></tr>
<tr class="separator:a57d28573876dd89be70cd78b9302f461"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a8c86e48ef3180201cc97cb928abd66ca"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d74/a00099.php#a8c86e48ef3180201cc97cb928abd66ca">Window</a> (QWidget *parent=nullptr)</td></tr>
<tr class="memdesc:a8c86e48ef3180201cc97cb928abd66ca"><td class="mdescLeft">&#160;</td><td class="mdescRight">The constructor.  <a href="#a8c86e48ef3180201cc97cb928abd66ca">More...</a><br /></td></tr>
<tr class="separator:a8c86e48ef3180201cc97cb928abd66ca"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a245d821e6016fa1f6970ccbbedd635f6"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d74/a00099.php#a245d821e6016fa1f6970ccbbedd635f6">~Window</a> ()</td></tr>
<tr class="memdesc:a245d821e6016fa1f6970ccbbedd635f6"><td class="mdescLeft">&#160;</td><td class="mdescRight">The destructor.  <a href="#a245d821e6016fa1f6970ccbbedd635f6">More...</a><br /></td></tr>
<tr class="separator:a245d821e6016fa1f6970ccbbedd635f6"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a008e887882941bcd08b6439dc001ea51"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d74/a00099.php#a008e887882941bcd08b6439dc001ea51">setWindowTitle</a> (const QString &amp;title)</td></tr>
<tr class="memdesc:a008e887882941bcd08b6439dc001ea51"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the window title.  <a href="#a008e887882941bcd08b6439dc001ea51">More...</a><br /></td></tr>
<tr class="separator:a008e887882941bcd08b6439dc001ea51"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8c65cb42e811de87be8743af6b9d21ed"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d74/a00099.php#a8c65cb42e811de87be8743af6b9d21ed">setCentralWidget</a> (QWidget *widget)</td></tr>
<tr class="memdesc:a8c65cb42e811de87be8743af6b9d21ed"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the central widget.  <a href="#a8c65cb42e811de87be8743af6b9d21ed">More...</a><br /></td></tr>
<tr class="separator:a8c65cb42e811de87be8743af6b9d21ed"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2983759dc6be4f8da44eff6069b2d3c8"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d74/a00099.php#a2983759dc6be4f8da44eff6069b2d3c8">setSize</a> (int w, int h)</td></tr>
<tr class="memdesc:a2983759dc6be4f8da44eff6069b2d3c8"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the window size.  <a href="#a2983759dc6be4f8da44eff6069b2d3c8">More...</a><br /></td></tr>
<tr class="separator:a2983759dc6be4f8da44eff6069b2d3c8"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4cec8e761a776437c9886d6982c22a54"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d74/a00099.php#a4cec8e761a776437c9886d6982c22a54">setMargin</a> (int m)</td></tr>
<tr class="memdesc:a4cec8e761a776437c9886d6982c22a54"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the window margin.  <a href="#a4cec8e761a776437c9886d6982c22a54">More...</a><br /></td></tr>
<tr class="separator:a4cec8e761a776437c9886d6982c22a54"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aad09788fdd6171092b43f31a91a384a2"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d74/a00099.php#aad09788fdd6171092b43f31a91a384a2">setMargin</a> (int t, int r, int b, int l)</td></tr>
<tr class="memdesc:aad09788fdd6171092b43f31a91a384a2"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the window margin.  <a href="#aad09788fdd6171092b43f31a91a384a2">More...</a><br /></td></tr>
<tr class="separator:aad09788fdd6171092b43f31a91a384a2"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a673240610da13a2424d4a7591fb19026"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d74/a00099.php#a673240610da13a2424d4a7591fb19026">fullscreen</a> ()</td></tr>
<tr class="memdesc:a673240610da13a2424d4a7591fb19026"><td class="mdescLeft">&#160;</td><td class="mdescRight">Call to fullscreen or unfullscreen the window.  <a href="#a673240610da13a2424d4a7591fb19026">More...</a><br /></td></tr>
<tr class="separator:a673240610da13a2424d4a7591fb19026"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a97078387be519b16401c3bb0f299aa01"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d74/a00099.php#a97078387be519b16401c3bb0f299aa01">minimize</a> ()</td></tr>
<tr class="memdesc:a97078387be519b16401c3bb0f299aa01"><td class="mdescLeft">&#160;</td><td class="mdescRight">Call to minimize the window.  <a href="#a97078387be519b16401c3bb0f299aa01">More...</a><br /></td></tr>
<tr class="separator:a97078387be519b16401c3bb0f299aa01"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad21ca1bd9a5c01411800f931bd7b1f7d"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d74/a00099.php#ad21ca1bd9a5c01411800f931bd7b1f7d">quit</a> ()</td></tr>
<tr class="memdesc:ad21ca1bd9a5c01411800f931bd7b1f7d"><td class="mdescLeft">&#160;</td><td class="mdescRight">Call to close the window.  <a href="#ad21ca1bd9a5c01411800f931bd7b1f7d">More...</a><br /></td></tr>
<tr class="separator:ad21ca1bd9a5c01411800f931bd7b1f7d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pub_methods_a00095"><td colspan="2" onclick="javascript:toggleInherit('pub_methods_a00095')"><img src="../../closed.png" alt="-"/>&#160;Public Member Functions inherited from <a class="el" href="../../d9/d77/a00095.php">Widget</a></td></tr>
<tr class="memitem:ace1aa23652eb4425355a81760b39fd37 inherit pub_methods_a00095"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d9/d77/a00095.php#ace1aa23652eb4425355a81760b39fd37">Widget</a> (QWidget *parent=nullptr)</td></tr>
<tr class="memdesc:ace1aa23652eb4425355a81760b39fd37 inherit pub_methods_a00095"><td class="mdescLeft">&#160;</td><td class="mdescRight">Create a QWidget.  <a href="../../d9/d77/a00095.php#ace1aa23652eb4425355a81760b39fd37">More...</a><br /></td></tr>
<tr class="separator:ace1aa23652eb4425355a81760b39fd37 inherit pub_methods_a00095"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a714cf798aadb4d615f6f60a355382c02 inherit pub_methods_a00095"><td class="memItemLeft" align="right" valign="top">virtual&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d9/d77/a00095.php#a714cf798aadb4d615f6f60a355382c02">~Widget</a> ()</td></tr>
<tr class="separator:a714cf798aadb4d615f6f60a355382c02 inherit pub_methods_a00095"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pro-methods"></a>
Protected Member Functions</h2></td></tr>
<tr class="memitem:a677a2c1046a84743e709515f5618b1e8"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d74/a00099.php#a677a2c1046a84743e709515f5618b1e8">showEvent</a> (QShowEvent *event)</td></tr>
<tr class="memdesc:a677a2c1046a84743e709515f5618b1e8"><td class="mdescLeft">&#160;</td><td class="mdescRight">The show event of the window.  <a href="#a677a2c1046a84743e709515f5618b1e8">More...</a><br /></td></tr>
<tr class="separator:a677a2c1046a84743e709515f5618b1e8"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1b653d42eb4810a8c0be48dc65d98b3a"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d74/a00099.php#a1b653d42eb4810a8c0be48dc65d98b3a">paintEvent</a> (QPaintEvent *event)</td></tr>
<tr class="memdesc:a1b653d42eb4810a8c0be48dc65d98b3a"><td class="mdescLeft">&#160;</td><td class="mdescRight">The paint event of the window.  <a href="#a1b653d42eb4810a8c0be48dc65d98b3a">More...</a><br /></td></tr>
<tr class="separator:a1b653d42eb4810a8c0be48dc65d98b3a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3d72edbec3fed3709ea3d374973c70b4"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d74/a00099.php#a3d72edbec3fed3709ea3d374973c70b4">resizeEvent</a> (QResizeEvent *event)</td></tr>
<tr class="memdesc:a3d72edbec3fed3709ea3d374973c70b4"><td class="mdescLeft">&#160;</td><td class="mdescRight">The resize event of the window.  <a href="#a3d72edbec3fed3709ea3d374973c70b4">More...</a><br /></td></tr>
<tr class="separator:a3d72edbec3fed3709ea3d374973c70b4"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1ce5696d3fac4e90e6c9fbd0477d0f9d"><td class="memItemLeft" align="right" valign="top">virtual void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d74/a00099.php#a1ce5696d3fac4e90e6c9fbd0477d0f9d">drawBackground</a> (QPixmap *cache)</td></tr>
<tr class="memdesc:a1ce5696d3fac4e90e6c9fbd0477d0f9d"><td class="mdescLeft">&#160;</td><td class="mdescRight">Draw the background of the window.  <a href="#a1ce5696d3fac4e90e6c9fbd0477d0f9d">More...</a><br /></td></tr>
<tr class="separator:a1ce5696d3fac4e90e6c9fbd0477d0f9d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:acbed45e30a51c6855e5e6ea88197b161"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d74/a00099.php#acbed45e30a51c6855e5e6ea88197b161">drawDefaultBackground</a> (QPixmap *cache)</td></tr>
<tr class="memdesc:acbed45e30a51c6855e5e6ea88197b161"><td class="mdescLeft">&#160;</td><td class="mdescRight">Draw the default background of the window.  <a href="#acbed45e30a51c6855e5e6ea88197b161">More...</a><br /></td></tr>
<tr class="separator:acbed45e30a51c6855e5e6ea88197b161"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3f710c0adafe15f27766f70a1c5b4dee"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d74/a00099.php#a3f710c0adafe15f27766f70a1c5b4dee">setBackground</a> (QPixmap *cache=nullptr)</td></tr>
<tr class="memdesc:a3f710c0adafe15f27766f70a1c5b4dee"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the background window.  <a href="#a3f710c0adafe15f27766f70a1c5b4dee">More...</a><br /></td></tr>
<tr class="separator:a3f710c0adafe15f27766f70a1c5b4dee"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a85b13ae29ce6f9aa9ffb7408b0ddd4b7"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d74/a00099.php#a85b13ae29ce6f9aa9ffb7408b0ddd4b7">enableResize</a> (bool enable)</td></tr>
<tr class="memdesc:a85b13ae29ce6f9aa9ffb7408b0ddd4b7"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set if yes or no the window can be resized.  <a href="#a85b13ae29ce6f9aa9ffb7408b0ddd4b7">More...</a><br /></td></tr>
<tr class="separator:a85b13ae29ce6f9aa9ffb7408b0ddd4b7"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8ad2a767e19299b153f9bc0457f13114"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d74/a00099.php#a8ad2a767e19299b153f9bc0457f13114">showTitlebar</a> (bool enable)</td></tr>
<tr class="memdesc:a8ad2a767e19299b153f9bc0457f13114"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set the titlebar visibility.  <a href="#a8ad2a767e19299b153f9bc0457f13114">More...</a><br /></td></tr>
<tr class="separator:a8ad2a767e19299b153f9bc0457f13114"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pro-attribs"></a>
Protected Attributes</h2></td></tr>
<tr class="memitem:a065e43061d8abb3717302dc1acf139c3"><td class="memItemLeft" align="right" valign="top">QPixmap *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d74/a00099.php#a065e43061d8abb3717302dc1acf139c3">m_Cache</a></td></tr>
<tr class="separator:a065e43061d8abb3717302dc1acf139c3"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>A custom window. </p>

<p class="definition">Definition at line <a class="el" href="../../d8/d41/a00038_source.php#l00022">22</a> of file <a class="el" href="../../d8/d41/a00038_source.php">Window.hpp</a>.</p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a id="a8c86e48ef3180201cc97cb928abd66ca"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a8c86e48ef3180201cc97cb928abd66ca">&#9670;&nbsp;</a></span>Window()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">Window::Window </td>
          <td>(</td>
          <td class="paramtype">QWidget *&#160;</td>
          <td class="paramname"><em>parent</em> = <code>nullptr</code></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>The constructor. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">parent</td><td>The parent widget </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a id="a245d821e6016fa1f6970ccbbedd635f6"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a245d821e6016fa1f6970ccbbedd635f6">&#9670;&nbsp;</a></span>~Window()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">Window::~Window </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>The destructor. </p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a id="a1ce5696d3fac4e90e6c9fbd0477d0f9d"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a1ce5696d3fac4e90e6c9fbd0477d0f9d">&#9670;&nbsp;</a></span>drawBackground()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">virtual void Window::drawBackground </td>
          <td>(</td>
          <td class="paramtype">QPixmap *&#160;</td>
          <td class="paramname"><em>cache</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span><span class="mlabel">virtual</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Draw the background of the window. </p>
<p>The method to overload to draw a personnalized background The default content is { this-&gt;<a class="el" href="../../da/d74/a00099.php#a3f710c0adafe15f27766f70a1c5b4dee" title="Set the background window. ">setBackground()</a>; } </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">cache</td><td>The pixmap to draw as the background </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

</div>
</div>
<a id="acbed45e30a51c6855e5e6ea88197b161"></a>
<h2 class="memtitle"><span class="permalink"><a href="#acbed45e30a51c6855e5e6ea88197b161">&#9670;&nbsp;</a></span>drawDefaultBackground()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Window::drawDefaultBackground </td>
          <td>(</td>
          <td class="paramtype">QPixmap *&#160;</td>
          <td class="paramname"><em>cache</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Draw the default background of the window. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">cache</td><td>The pixmap to draw the default background </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

</div>
</div>
<a id="a85b13ae29ce6f9aa9ffb7408b0ddd4b7"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a85b13ae29ce6f9aa9ffb7408b0ddd4b7">&#9670;&nbsp;</a></span>enableResize()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Window::enableResize </td>
          <td>(</td>
          <td class="paramtype">bool&#160;</td>
          <td class="paramname"><em>enable</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Set if yes or no the window can be resized. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">enable</td><td><b>true</b> or <b>false</b> </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

</div>
</div>
<a id="a673240610da13a2424d4a7591fb19026"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a673240610da13a2424d4a7591fb19026">&#9670;&nbsp;</a></span>fullscreen()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void Window::fullscreen </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Call to fullscreen or unfullscreen the window. </p>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

</div>
</div>
<a id="a801605000f4773291ab5b5e07c6155bc"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a801605000f4773291ab5b5e07c6155bc">&#9670;&nbsp;</a></span>Fullscreen</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Window::Fullscreen </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">signal</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Call when the window as to be fullscreened or not. </p>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

</div>
</div>
<a id="a97078387be519b16401c3bb0f299aa01"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a97078387be519b16401c3bb0f299aa01">&#9670;&nbsp;</a></span>minimize()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void Window::minimize </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Call to minimize the window. </p>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

</div>
</div>
<a id="a1b653d42eb4810a8c0be48dc65d98b3a"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a1b653d42eb4810a8c0be48dc65d98b3a">&#9670;&nbsp;</a></span>paintEvent()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Window::paintEvent </td>
          <td>(</td>
          <td class="paramtype">QPaintEvent *&#160;</td>
          <td class="paramname"><em>event</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span><span class="mlabel">virtual</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>The paint event of the window. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">event</td><td>The event sended </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

<p>Reimplemented from <a class="el" href="../../d9/d77/a00095.php#a0ce51928b65b53bd72575e7138e3238c">Widget</a>.</p>

</div>
</div>
<a id="ad21ca1bd9a5c01411800f931bd7b1f7d"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ad21ca1bd9a5c01411800f931bd7b1f7d">&#9670;&nbsp;</a></span>quit()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void Window::quit </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Call to close the window. </p>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

</div>
</div>
<a id="a57d28573876dd89be70cd78b9302f461"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a57d28573876dd89be70cd78b9302f461">&#9670;&nbsp;</a></span>Quit</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Window::Quit </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">signal</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Call when the window has to be closed. </p>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

</div>
</div>
<a id="a16563366618e73bee12d9cd5358c57ea"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a16563366618e73bee12d9cd5358c57ea">&#9670;&nbsp;</a></span>Reduice</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Window::Reduice </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">signal</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Call when the window has to be reduice or not. </p>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

</div>
</div>
<a id="a3d72edbec3fed3709ea3d374973c70b4"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a3d72edbec3fed3709ea3d374973c70b4">&#9670;&nbsp;</a></span>resizeEvent()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Window::resizeEvent </td>
          <td>(</td>
          <td class="paramtype">QResizeEvent *&#160;</td>
          <td class="paramname"><em>event</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>The resize event of the window. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">event</td><td>The event sended </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

</div>
</div>
<a id="a3f710c0adafe15f27766f70a1c5b4dee"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a3f710c0adafe15f27766f70a1c5b4dee">&#9670;&nbsp;</a></span>setBackground()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Window::setBackground </td>
          <td>(</td>
          <td class="paramtype">QPixmap *&#160;</td>
          <td class="paramname"><em>cache</em> = <code>nullptr</code></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Set the background window. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">cache</td><td>The pixmap to draw as the background </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

</div>
</div>
<a id="a8c65cb42e811de87be8743af6b9d21ed"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a8c65cb42e811de87be8743af6b9d21ed">&#9670;&nbsp;</a></span>setCentralWidget()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void Window::setCentralWidget </td>
          <td>(</td>
          <td class="paramtype">QWidget *&#160;</td>
          <td class="paramname"><em>widget</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Set the central widget. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">widget</td><td>The central widget </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

</div>
</div>
<a id="a4cec8e761a776437c9886d6982c22a54"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a4cec8e761a776437c9886d6982c22a54">&#9670;&nbsp;</a></span>setMargin() <span class="overload">[1/2]</span></h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Window::setMargin </td>
          <td>(</td>
          <td class="paramtype">int&#160;</td>
          <td class="paramname"><em>m</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Set the window margin. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">m</td><td>The size of all the margins </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

<p class="definition">Definition at line <a class="el" href="../../d8/d41/a00038_source.php#l00058">58</a> of file <a class="el" href="../../d8/d41/a00038_source.php">Window.hpp</a>.</p>
<div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../da/d74/a00099_a4cec8e761a776437c9886d6982c22a54_cgraph.png" border="0" usemap="#da/d74/a00099_a4cec8e761a776437c9886d6982c22a54_cgraph" alt=""/></div>
<map name="da/d74/a00099_a4cec8e761a776437c9886d6982c22a54_cgraph" id="da/d74/a00099_a4cec8e761a776437c9886d6982c22a54_cgraph">
<area shape="rect" id="node2" href="../../da/d74/a00099.php#a673240610da13a2424d4a7591fb19026" title="Call to fullscreen or unfullscreen the window. " alt="" coords="229,5,363,32"/>
<area shape="rect" id="node3" href="../../da/d74/a00099.php#a97078387be519b16401c3bb0f299aa01" title="Call to minimize the window. " alt="" coords="231,56,361,83"/>
<area shape="rect" id="node4" href="../../da/d74/a00099.php#ad21ca1bd9a5c01411800f931bd7b1f7d" title="Call to close the window. " alt="" coords="247,107,345,133"/>
<area shape="rect" id="node5" href="../../da/d74/a00099.php#a677a2c1046a84743e709515f5618b1e8" title="The show event of the window. " alt="" coords="225,157,367,184"/>
<area shape="rect" id="node6" href="../../da/d74/a00099.php#a1b653d42eb4810a8c0be48dc65d98b3a" title="The paint event of the window. " alt="" coords="227,208,365,235"/>
<area shape="rect" id="node7" href="../../da/d74/a00099.php#a3d72edbec3fed3709ea3d374973c70b4" title="The resize event of the window. " alt="" coords="223,259,369,285"/>
<area shape="rect" id="node8" href="../../da/d74/a00099.php#a1ce5696d3fac4e90e6c9fbd0477d0f9d" title="Draw the background of the window. " alt="" coords="209,309,383,336"/>
<area shape="rect" id="node9" href="../../da/d74/a00099.php#acbed45e30a51c6855e5e6ea88197b161" title="Draw the default background of the window. " alt="" coords="188,360,404,387"/>
<area shape="rect" id="node10" href="../../da/d74/a00099.php#a3f710c0adafe15f27766f70a1c5b4dee" title="Set the background window. " alt="" coords="214,411,378,437"/>
<area shape="rect" id="node11" href="../../da/d74/a00099.php#a85b13ae29ce6f9aa9ffb7408b0ddd4b7" title="Set if yes or no the window can be resized. " alt="" coords="218,461,374,488"/>
<area shape="rect" id="node12" href="../../da/d74/a00099.php#a8ad2a767e19299b153f9bc0457f13114" title="Set the titlebar visibility. " alt="" coords="221,512,371,539"/>
</map>
</div>

</div>
</div>
<a id="aad09788fdd6171092b43f31a91a384a2"></a>
<h2 class="memtitle"><span class="permalink"><a href="#aad09788fdd6171092b43f31a91a384a2">&#9670;&nbsp;</a></span>setMargin() <span class="overload">[2/2]</span></h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void Window::setMargin </td>
          <td>(</td>
          <td class="paramtype">int&#160;</td>
          <td class="paramname"><em>t</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">int&#160;</td>
          <td class="paramname"><em>r</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">int&#160;</td>
          <td class="paramname"><em>b</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">int&#160;</td>
          <td class="paramname"><em>l</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Set the window margin. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">t</td><td>The top margin </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">r</td><td>The right margin </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">b</td><td>The bottom margin </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">l</td><td>The left margin </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

</div>
</div>
<a id="a2983759dc6be4f8da44eff6069b2d3c8"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a2983759dc6be4f8da44eff6069b2d3c8">&#9670;&nbsp;</a></span>setSize()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void Window::setSize </td>
          <td>(</td>
          <td class="paramtype">int&#160;</td>
          <td class="paramname"><em>w</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">int&#160;</td>
          <td class="paramname"><em>h</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Set the window size. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">w</td><td>The window width </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">h</td><td>The window height </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

</div>
</div>
<a id="a008e887882941bcd08b6439dc001ea51"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a008e887882941bcd08b6439dc001ea51">&#9670;&nbsp;</a></span>setWindowTitle()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void Window::setWindowTitle </td>
          <td>(</td>
          <td class="paramtype">const QString &amp;&#160;</td>
          <td class="paramname"><em>title</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Set the window title. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">title</td><td>The title </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

</div>
</div>
<a id="a677a2c1046a84743e709515f5618b1e8"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a677a2c1046a84743e709515f5618b1e8">&#9670;&nbsp;</a></span>showEvent()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Window::showEvent </td>
          <td>(</td>
          <td class="paramtype">QShowEvent *&#160;</td>
          <td class="paramname"><em>event</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>The show event of the window. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">event</td><td>The event sended </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

</div>
</div>
<a id="a8ad2a767e19299b153f9bc0457f13114"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a8ad2a767e19299b153f9bc0457f13114">&#9670;&nbsp;</a></span>showTitlebar()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Window::showTitlebar </td>
          <td>(</td>
          <td class="paramtype">bool&#160;</td>
          <td class="paramname"><em>enable</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Set the titlebar visibility. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">enable</td><td><b>true</b> or <b>false</b> </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

</div>
</div>
<a id="a1f3319d59097b7c9e5bde545e6867c1b"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a1f3319d59097b7c9e5bde545e6867c1b">&#9670;&nbsp;</a></span>TitleBarShowState</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Window::TitleBarShowState </td>
          <td>(</td>
          <td class="paramtype">bool&#160;</td>
          <td class="paramname"><em>state</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">signal</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Call when the state of the titlebar is changed show/hide. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">state</td><td>The state visible or hidden </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

</div>
</div>
<a id="a9b8e592bf73f07ec549125eb6367395c"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a9b8e592bf73f07ec549125eb6367395c">&#9670;&nbsp;</a></span>WindowResizeChanged</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Window::WindowResizeChanged </td>
          <td>(</td>
          <td class="paramtype">bool&#160;</td>
          <td class="paramname"><em>state</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">signal</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Call when the window is resized. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">state</td><td>The state resized or unresized </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

</div>
</div>
<a id="a56ced9e90dad8415ce9ba9ccdb8f50c7"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a56ced9e90dad8415ce9ba9ccdb8f50c7">&#9670;&nbsp;</a></span>WindowTitleChanged</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void Window::WindowTitleChanged </td>
          <td>(</td>
          <td class="paramtype">QString&#160;</td>
          <td class="paramname"><em>title</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">signal</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Call when the window title is changed. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">title</td><td>The title of the window </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

</div>
</div>
<h2 class="groupheader">Member Data Documentation</h2>
<a id="a065e43061d8abb3717302dc1acf139c3"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a065e43061d8abb3717302dc1acf139c3">&#9670;&nbsp;</a></span>m_Cache</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">QPixmap* Window::m_Cache</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p class="definition">Definition at line <a class="el" href="../../d8/d41/a00038_source.php#l00185">185</a> of file <a class="el" href="../../d8/d41/a00038_source.php">Window.hpp</a>.</p>

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li><a class="el" href="../../d8/d41/a00038_source.php">Window.hpp</a></li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="../../da/d74/a00099.php">Window</a></li>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.13 </li>
  </ul>
</div>
</body>
</html>
