<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.13"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>Qt: QtDefines.hpp File Reference</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Qt
   &#160;<span id="projectnumber">1.0</span>
   </div>
   <div id="projectbrief">Specific widgets for Qt</div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d4/d51/a00017.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="headertitle">
<div class="title">QtDefines.hpp File Reference</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock"><code>#include &lt;QtWidgets&gt;</code><br />
<code>#include &quot;<a class="el" href="../../d4/d8c/a00035_source.php">Widget.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../d7/d46/a00002_source.php">DrawScene.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../d4/dee/a00008_source.php">GraphScene.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../d3/d52/a00023_source.php">Scene.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../d6/d5b/a00026_source.php">Spacers.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../db/db2/a00020_source.php">QtFunctions.hpp</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="../../dd/dad/a00005_source.php">Font.hpp</a>&quot;</code><br />
<code>#include &quot;C++/C++.hpp&quot;</code><br />
</div><div class="textblock"><div class="dynheader">
Include dependency graph for QtDefines.hpp:</div>
<div class="dyncontent">
<div class="center"><img src="../../d1/d2b/a00018.png" border="0" usemap="#QtDefines_8hpp" alt=""/></div>
<map name="QtDefines_8hpp" id="QtDefines_8hpp">
<area shape="rect" id="node3" href="../../d4/d8c/a00035.php" title="Widget.hpp" alt="" coords="732,155,820,181"/>
<area shape="rect" id="node4" href="../../d7/d46/a00002.php" title="DrawScene.hpp" alt="" coords="5,80,120,107"/>
<area shape="rect" id="node5" href="../../d3/d52/a00023.php" title="Scene.hpp" alt="" coords="13,155,97,181"/>
<area shape="rect" id="node7" href="../../d4/dee/a00008.php" title="GraphScene.hpp" alt="" coords="243,80,362,107"/>
<area shape="rect" id="node12" href="../../d6/d5b/a00026.php" title="Spacers.hpp" alt="" coords="783,80,878,107"/>
<area shape="rect" id="node13" href="../../db/db2/a00020.php" title="QtFunctions.hpp" alt="" coords="441,80,559,107"/>
<area shape="rect" id="node15" href="../../dd/dad/a00005.php" title="Font.hpp" alt="" coords="583,80,657,107"/>
</map>
</div>
</div><div class="textblock"><div class="dynheader">
This graph shows which files directly or indirectly include this file:</div>
<div class="dyncontent">
<div class="center"><img src="../../dd/da2/a00019.png" border="0" usemap="#QtDefines_8hppdep" alt=""/></div>
<map name="QtDefines_8hppdep" id="QtDefines_8hppdep">
<area shape="rect" id="node2" href="../../d2/de7/a00014.php" title="Qt.hpp" alt="" coords="97,304,159,331"/>
<area shape="rect" id="node5" href="../../dd/d32/a00041.php" title="WindowButton.hpp" alt="" coords="125,80,257,107"/>
<area shape="rect" id="node3" href="../../dc/d87/a00032.php" title="TableWidget.hpp" alt="" coords="5,379,125,405"/>
<area shape="rect" id="node4" href="../../d5/d16/a00029.php" title="String.hpp" alt="" coords="150,379,231,405"/>
<area shape="rect" id="node6" href="../../d5/df9/a00044.php" title="WindowTitleBar.hpp" alt="" coords="123,155,261,181"/>
<area shape="rect" id="node7" href="../../d8/d41/a00038.php" title="Window.hpp" alt="" coords="134,229,229,256"/>
</map>
</div>
</div>
<p><a href="../../d4/d51/a00017_source.php">Go to the source code of this file.</a></p>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><dl class="section author"><dt>Author</dt><dd>Mathias CABIOCH-DELALANDE </dd></dl>
<dl class="section date"><dt>Date</dt><dd>08 juin 2018 </dd></dl>

<p class="definition">Definition in file <a class="el" href="../../d4/d51/a00017_source.php">QtDefines.hpp</a>.</p>
</div></div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="../../dir_badfd550b617ce52cc73ed1c8c9513f6.php">Algo</a></li><li class="navelem"><a class="el" href="../../dir_a02ca41573efbfa5a2fd3c2b5453f5e3.php">QTTests</a></li><li class="navelem"><a class="el" href="../../dir_241af41b803d499a248aecae0c64f982.php">Widgets</a></li><li class="navelem"><a class="el" href="../../d4/d51/a00017.php">QtDefines.hpp</a></li>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.13 </li>
  </ul>
</div>
</body>
</html>
