<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.13"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>Qt: Widget Class Reference</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Qt
   &#160;<span id="projectnumber">1.0</span>
   </div>
   <div id="projectbrief">Specific widgets for Qt</div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('d9/d77/a00095.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pro-methods">Protected Member Functions</a> &#124;
<a href="../../d1/dc1/a00092.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">Widget Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>Create a personnalized <a class="el" href="../../d9/d77/a00095.php" title="Create a personnalized Widget. ">Widget</a>.  
 <a href="../../d9/d77/a00095.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="../../d4/d8c/a00035_source.php">Widget.hpp</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for Widget:</div>
<div class="dyncontent">
<div class="center"><img src="../../dc/d54/a00094.png" border="0" usemap="#Widget_inherit__map" alt="Inheritance graph"/></div>
<map name="Widget_inherit__map" id="Widget_inherit__map">
<area shape="rect" id="node3" href="../../da/d82/a00091.php" title="Create a personnalized TableWidget. " alt="" coords="5,155,100,181"/>
<area shape="rect" id="node4" href="../../da/d74/a00099.php" title="A custom window. " alt="" coords="125,155,194,181"/>
<area shape="rect" id="node5" href="../../df/d98/a00107.php" title="The titlebar of the Window class. " alt="" coords="218,155,333,181"/>
</map>
<center><span class="legend">[<a target="top" href="../../graph_legend.php">legend</a>]</span></center></div>
<div class="dynheader">
Collaboration diagram for Widget:</div>
<div class="dyncontent">
<div class="center"><img src="../../d4/d7d/a00093.png" border="0" usemap="#Widget_coll__map" alt="Collaboration graph"/></div>
<center><span class="legend">[<a target="top" href="../../graph_legend.php">legend</a>]</span></center></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:ace1aa23652eb4425355a81760b39fd37"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d9/d77/a00095.php#ace1aa23652eb4425355a81760b39fd37">Widget</a> (QWidget *parent=nullptr)</td></tr>
<tr class="memdesc:ace1aa23652eb4425355a81760b39fd37"><td class="mdescLeft">&#160;</td><td class="mdescRight">Create a QWidget.  <a href="#ace1aa23652eb4425355a81760b39fd37">More...</a><br /></td></tr>
<tr class="separator:ace1aa23652eb4425355a81760b39fd37"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a714cf798aadb4d615f6f60a355382c02"><td class="memItemLeft" align="right" valign="top">virtual&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d9/d77/a00095.php#a714cf798aadb4d615f6f60a355382c02">~Widget</a> ()</td></tr>
<tr class="separator:a714cf798aadb4d615f6f60a355382c02"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pro-methods"></a>
Protected Member Functions</h2></td></tr>
<tr class="memitem:a0ce51928b65b53bd72575e7138e3238c"><td class="memItemLeft" align="right" valign="top">virtual void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d9/d77/a00095.php#a0ce51928b65b53bd72575e7138e3238c">paintEvent</a> (QPaintEvent *event)</td></tr>
<tr class="memdesc:a0ce51928b65b53bd72575e7138e3238c"><td class="mdescLeft">&#160;</td><td class="mdescRight">Overload of the paintEvent of QWidget to use stylesheets.  <a href="#a0ce51928b65b53bd72575e7138e3238c">More...</a><br /></td></tr>
<tr class="separator:a0ce51928b65b53bd72575e7138e3238c"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>Create a personnalized <a class="el" href="../../d9/d77/a00095.php" title="Create a personnalized Widget. ">Widget</a>. </p>

<p class="definition">Definition at line <a class="el" href="../../d4/d8c/a00035_source.php#l00017">17</a> of file <a class="el" href="../../d4/d8c/a00035_source.php">Widget.hpp</a>.</p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a id="ace1aa23652eb4425355a81760b39fd37"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ace1aa23652eb4425355a81760b39fd37">&#9670;&nbsp;</a></span>Widget()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">Widget::Widget </td>
          <td>(</td>
          <td class="paramtype">QWidget *&#160;</td>
          <td class="paramname"><em>parent</em> = <code>nullptr</code></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Create a QWidget. </p>

<p class="definition">Definition at line <a class="el" href="../../d4/d8c/a00035_source.php#l00021">21</a> of file <a class="el" href="../../d4/d8c/a00035_source.php">Widget.hpp</a>.</p>

</div>
</div>
<a id="a714cf798aadb4d615f6f60a355382c02"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a714cf798aadb4d615f6f60a355382c02">&#9670;&nbsp;</a></span>~Widget()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">virtual Widget::~Widget </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span><span class="mlabel">virtual</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p class="definition">Definition at line <a class="el" href="../../d4/d8c/a00035_source.php#l00022">22</a> of file <a class="el" href="../../d4/d8c/a00035_source.php">Widget.hpp</a>.</p>
<div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="../../d9/d77/a00095_a714cf798aadb4d615f6f60a355382c02_cgraph.png" border="0" usemap="#d9/d77/a00095_a714cf798aadb4d615f6f60a355382c02_cgraph" alt=""/></div>
<map name="d9/d77/a00095_a714cf798aadb4d615f6f60a355382c02_cgraph" id="d9/d77/a00095_a714cf798aadb4d615f6f60a355382c02_cgraph">
<area shape="rect" id="node2" href="../../d9/d77/a00095.php#a0ce51928b65b53bd72575e7138e3238c" title="Overload of the paintEvent of QWidget to use stylesheets. " alt="" coords="173,5,307,32"/>
</map>
</div>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a id="a0ce51928b65b53bd72575e7138e3238c"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a0ce51928b65b53bd72575e7138e3238c">&#9670;&nbsp;</a></span>paintEvent()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">virtual void Widget::paintEvent </td>
          <td>(</td>
          <td class="paramtype">QPaintEvent *&#160;</td>
          <td class="paramname"><em>event</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span><span class="mlabel">virtual</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Overload of the paintEvent of QWidget to use stylesheets. </p>

<p>Reimplemented in <a class="el" href="../../da/d74/a00099.php#a1b653d42eb4810a8c0be48dc65d98b3a">Window</a>, and <a class="el" href="../../df/d98/a00107.php#a43be58f98c5d53bce63cd96999e7c71a">WindowTitleBar</a>.</p>

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li><a class="el" href="../../d4/d8c/a00035_source.php">Widget.hpp</a></li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="../../d9/d77/a00095.php">Widget</a></li>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.13 </li>
  </ul>
</div>
</body>
</html>
