<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.13"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>Qt: Lines.hpp Source File</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Qt
   &#160;<span id="projectnumber">1.0</span>
   </div>
   <div id="projectbrief">Specific widgets for Qt</div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('da/d45/a00011_source.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="headertitle">
<div class="title">Lines.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="../../da/d45/a00011.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00008"></a><span class="lineno">    8</span>&#160;<span class="preprocessor">#ifndef HEADER_QLINE</span></div><div class="line"><a name="l00009"></a><span class="lineno">    9</span>&#160;<span class="preprocessor">#define HEADER_QLINE</span></div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;</div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;<span class="preprocessor">#include &lt;QtWidgets&gt;</span></div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;</div><div class="line"><a name="l00017"></a><span class="lineno"><a class="line" href="../../d1/d6f/a00063.php">   17</a></span>&#160;<span class="keyword">class </span><a class="code" href="../../d1/d6f/a00063.php">Line</a> : <span class="keyword">public</span> QFrame {</div><div class="line"><a name="l00018"></a><span class="lineno">   18</span>&#160;    Q_OBJECT</div><div class="line"><a name="l00019"></a><span class="lineno">   19</span>&#160;    <span class="keyword">public</span>:</div><div class="line"><a name="l00021"></a><span class="lineno">   21</span>&#160;        <a class="code" href="../../d1/d6f/a00063.php#a5bc71a96071093bc00a3ad5d58526b99">Line</a>(QWidget* parent, QFrame::Shape shape);</div><div class="line"><a name="l00022"></a><span class="lineno"><a class="line" href="../../d1/d6f/a00063.php#a4a95bafcefa28672b3999deb011b9e50">   22</a></span>&#160;        <span class="keyword">virtual</span> <a class="code" href="../../d1/d6f/a00063.php#a4a95bafcefa28672b3999deb011b9e50">~Line</a>(){}</div><div class="line"><a name="l00023"></a><span class="lineno">   23</span>&#160;};</div><div class="line"><a name="l00024"></a><span class="lineno">   24</span>&#160;</div><div class="line"><a name="l00029"></a><span class="lineno"><a class="line" href="../../dc/ddf/a00067.php">   29</a></span>&#160;<span class="keyword">class </span><a class="code" href="../../dc/ddf/a00067.php">HLine</a> : <span class="keyword">public</span> <a class="code" href="../../d1/d6f/a00063.php">Line</a> {</div><div class="line"><a name="l00030"></a><span class="lineno">   30</span>&#160;    Q_OBJECT</div><div class="line"><a name="l00031"></a><span class="lineno">   31</span>&#160;    <span class="keyword">public</span>:</div><div class="line"><a name="l00033"></a><span class="lineno"><a class="line" href="../../dc/ddf/a00067.php#aa48630fb2b4fd09dbb4f03fd23f8dc9c">   33</a></span>&#160;        <a class="code" href="../../dc/ddf/a00067.php#aa48630fb2b4fd09dbb4f03fd23f8dc9c">HLine</a>(QWidget* parent = <span class="keyword">nullptr</span>) : <a class="code" href="../../d1/d6f/a00063.php">Line</a>(parent, QFrame::<a class="code" href="../../dc/ddf/a00067.php">HLine</a>) {}</div><div class="line"><a name="l00034"></a><span class="lineno"><a class="line" href="../../dc/ddf/a00067.php#ac107cd8335137b912fe56c3dc18763b0">   34</a></span>&#160;        <span class="keyword">virtual</span> <a class="code" href="../../dc/ddf/a00067.php#ac107cd8335137b912fe56c3dc18763b0">~HLine</a>(){}</div><div class="line"><a name="l00035"></a><span class="lineno">   35</span>&#160;};</div><div class="line"><a name="l00036"></a><span class="lineno">   36</span>&#160;</div><div class="line"><a name="l00041"></a><span class="lineno"><a class="line" href="../../d0/d89/a00071.php">   41</a></span>&#160;<span class="keyword">class </span><a class="code" href="../../d0/d89/a00071.php">VLine</a> : <span class="keyword">public</span> <a class="code" href="../../d1/d6f/a00063.php">Line</a> {</div><div class="line"><a name="l00042"></a><span class="lineno">   42</span>&#160;    Q_OBJECT</div><div class="line"><a name="l00043"></a><span class="lineno">   43</span>&#160;    <span class="keyword">public</span>:</div><div class="line"><a name="l00045"></a><span class="lineno"><a class="line" href="../../d0/d89/a00071.php#a307595ec20b568173ae830da59b88b21">   45</a></span>&#160;        <a class="code" href="../../d0/d89/a00071.php#a307595ec20b568173ae830da59b88b21">VLine</a>(QWidget* parent = <span class="keyword">nullptr</span>) : <a class="code" href="../../d1/d6f/a00063.php">Line</a>(parent, QFrame::<a class="code" href="../../d0/d89/a00071.php">VLine</a>) {}</div><div class="line"><a name="l00046"></a><span class="lineno"><a class="line" href="../../d0/d89/a00071.php#a68b29e1f4862812e9c129238d183f48a">   46</a></span>&#160;        <span class="keyword">virtual</span> <a class="code" href="../../d0/d89/a00071.php#a68b29e1f4862812e9c129238d183f48a">~VLine</a>(){}</div><div class="line"><a name="l00047"></a><span class="lineno">   47</span>&#160;};</div><div class="line"><a name="l00048"></a><span class="lineno">   48</span>&#160;</div><div class="line"><a name="l00049"></a><span class="lineno">   49</span>&#160;<span class="preprocessor">#endif //HEADER_QLINE</span></div><div class="ttc" id="a00071_php"><div class="ttname"><a href="../../d0/d89/a00071.php">VLine</a></div><div class="ttdoc">Create a line. </div><div class="ttdef"><b>Definition:</b> <a href="../../da/d45/a00011_source.php#l00041">Lines.hpp:41</a></div></div>
<div class="ttc" id="a00067_php_aa48630fb2b4fd09dbb4f03fd23f8dc9c"><div class="ttname"><a href="../../dc/ddf/a00067.php#aa48630fb2b4fd09dbb4f03fd23f8dc9c">HLine::HLine</a></div><div class="ttdeci">HLine(QWidget *parent=nullptr)</div><div class="ttdoc">Create a HLine. </div><div class="ttdef"><b>Definition:</b> <a href="../../da/d45/a00011_source.php#l00033">Lines.hpp:33</a></div></div>
<div class="ttc" id="a00063_php_a4a95bafcefa28672b3999deb011b9e50"><div class="ttname"><a href="../../d1/d6f/a00063.php#a4a95bafcefa28672b3999deb011b9e50">Line::~Line</a></div><div class="ttdeci">virtual ~Line()</div><div class="ttdef"><b>Definition:</b> <a href="../../da/d45/a00011_source.php#l00022">Lines.hpp:22</a></div></div>
<div class="ttc" id="a00067_php_ac107cd8335137b912fe56c3dc18763b0"><div class="ttname"><a href="../../dc/ddf/a00067.php#ac107cd8335137b912fe56c3dc18763b0">HLine::~HLine</a></div><div class="ttdeci">virtual ~HLine()</div><div class="ttdef"><b>Definition:</b> <a href="../../da/d45/a00011_source.php#l00034">Lines.hpp:34</a></div></div>
<div class="ttc" id="a00071_php_a307595ec20b568173ae830da59b88b21"><div class="ttname"><a href="../../d0/d89/a00071.php#a307595ec20b568173ae830da59b88b21">VLine::VLine</a></div><div class="ttdeci">VLine(QWidget *parent=nullptr)</div><div class="ttdoc">Create a VLine. </div><div class="ttdef"><b>Definition:</b> <a href="../../da/d45/a00011_source.php#l00045">Lines.hpp:45</a></div></div>
<div class="ttc" id="a00063_php_a5bc71a96071093bc00a3ad5d58526b99"><div class="ttname"><a href="../../d1/d6f/a00063.php#a5bc71a96071093bc00a3ad5d58526b99">Line::Line</a></div><div class="ttdeci">Line(QWidget *parent, QFrame::Shape shape)</div><div class="ttdoc">Create a Line. </div></div>
<div class="ttc" id="a00071_php_a68b29e1f4862812e9c129238d183f48a"><div class="ttname"><a href="../../d0/d89/a00071.php#a68b29e1f4862812e9c129238d183f48a">VLine::~VLine</a></div><div class="ttdeci">virtual ~VLine()</div><div class="ttdef"><b>Definition:</b> <a href="../../da/d45/a00011_source.php#l00046">Lines.hpp:46</a></div></div>
<div class="ttc" id="a00067_php"><div class="ttname"><a href="../../dc/ddf/a00067.php">HLine</a></div><div class="ttdoc">Create a horizontal line. </div><div class="ttdef"><b>Definition:</b> <a href="../../da/d45/a00011_source.php#l00029">Lines.hpp:29</a></div></div>
<div class="ttc" id="a00063_php"><div class="ttname"><a href="../../d1/d6f/a00063.php">Line</a></div><div class="ttdoc">Create a line. </div><div class="ttdef"><b>Definition:</b> <a href="../../da/d45/a00011_source.php#l00017">Lines.hpp:17</a></div></div>
</div><!-- fragment --></div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="../../dir_badfd550b617ce52cc73ed1c8c9513f6.php">Algo</a></li><li class="navelem"><a class="el" href="../../dir_a02ca41573efbfa5a2fd3c2b5453f5e3.php">QTTests</a></li><li class="navelem"><a class="el" href="../../dir_241af41b803d499a248aecae0c64f982.php">Widgets</a></li><li class="navelem"><a class="el" href="../../da/d45/a00011.php">Lines.hpp</a></li>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.13 </li>
  </ul>
</div>
</body>
</html>
