<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.13"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>Qt: WindowTitleBar Class Reference</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Qt
   &#160;<span id="projectnumber">1.0</span>
   </div>
   <div id="projectbrief">Specific widgets for Qt</div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('df/d98/a00107.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#pub-slots">Public Slots</a> &#124;
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pro-methods">Protected Member Functions</a> &#124;
<a href="../../d0/dc2/a00104.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">WindowTitleBar Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>The titlebar of the <a class="el" href="../../da/d74/a00099.php" title="A custom window. ">Window</a> class.  
 <a href="../../df/d98/a00107.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="../../d5/df9/a00044_source.php">WindowTitleBar.hpp</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for WindowTitleBar:</div>
<div class="dyncontent">
<div class="center"><img src="../../d7/d70/a00106.png" border="0" usemap="#WindowTitleBar_inherit__map" alt="Inheritance graph"/></div>
<map name="WindowTitleBar_inherit__map" id="WindowTitleBar_inherit__map">
<area shape="rect" id="node2" href="../../d9/d77/a00095.php" title="Create a personnalized Widget. " alt="" coords="31,80,94,107"/>
</map>
<center><span class="legend">[<a target="top" href="../../graph_legend.php">legend</a>]</span></center></div>
<div class="dynheader">
Collaboration diagram for WindowTitleBar:</div>
<div class="dyncontent">
<div class="center"><img src="../../d3/d32/a00105.png" border="0" usemap="#WindowTitleBar_coll__map" alt="Collaboration graph"/></div>
<map name="WindowTitleBar_coll__map" id="WindowTitleBar_coll__map">
<area shape="rect" id="node2" href="../../d9/d77/a00095.php" title="Create a personnalized Widget. " alt="" coords="31,80,94,107"/>
</map>
<center><span class="legend">[<a target="top" href="../../graph_legend.php">legend</a>]</span></center></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-slots"></a>
Public Slots</h2></td></tr>
<tr class="memitem:a5a96b7bd195f625fc4ffb6c7fe180709"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d98/a00107.php#a5a96b7bd195f625fc4ffb6c7fe180709">UpdateWindowTitle</a> (QString title)</td></tr>
<tr class="memdesc:a5a96b7bd195f625fc4ffb6c7fe180709"><td class="mdescLeft">&#160;</td><td class="mdescRight">Update the window's title.  <a href="#a5a96b7bd195f625fc4ffb6c7fe180709">More...</a><br /></td></tr>
<tr class="separator:a5a96b7bd195f625fc4ffb6c7fe180709"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a91ce1aab8c3ed4a14554a1ddc32a87f1"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d98/a00107.php#a91ce1aab8c3ed4a14554a1ddc32a87f1">ApplyResizeChange</a> (bool state)</td></tr>
<tr class="memdesc:a91ce1aab8c3ed4a14554a1ddc32a87f1"><td class="mdescLeft">&#160;</td><td class="mdescRight">Apply the resize state change.  <a href="#a91ce1aab8c3ed4a14554a1ddc32a87f1">More...</a><br /></td></tr>
<tr class="separator:a91ce1aab8c3ed4a14554a1ddc32a87f1"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4def0f2b659a07381fe8abaedd90e303"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d98/a00107.php#a4def0f2b659a07381fe8abaedd90e303">ApplyTitleBarState</a> (bool state)</td></tr>
<tr class="memdesc:a4def0f2b659a07381fe8abaedd90e303"><td class="mdescLeft">&#160;</td><td class="mdescRight">Show or hide the titlebar.  <a href="#a4def0f2b659a07381fe8abaedd90e303">More...</a><br /></td></tr>
<tr class="separator:a4def0f2b659a07381fe8abaedd90e303"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aae235853885d03ddd070efb8fef2f4e1"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d98/a00107.php#aae235853885d03ddd070efb8fef2f4e1">Minimized</a> ()</td></tr>
<tr class="memdesc:aae235853885d03ddd070efb8fef2f4e1"><td class="mdescLeft">&#160;</td><td class="mdescRight">Minimize the window.  <a href="#aae235853885d03ddd070efb8fef2f4e1">More...</a><br /></td></tr>
<tr class="separator:aae235853885d03ddd070efb8fef2f4e1"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7d91818e1ef1189dc5c0524729a62e34"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d98/a00107.php#a7d91818e1ef1189dc5c0524729a62e34">Maximized</a> ()</td></tr>
<tr class="memdesc:a7d91818e1ef1189dc5c0524729a62e34"><td class="mdescLeft">&#160;</td><td class="mdescRight">Maximize the window.  <a href="#a7d91818e1ef1189dc5c0524729a62e34">More...</a><br /></td></tr>
<tr class="separator:a7d91818e1ef1189dc5c0524729a62e34"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1604ff5ed446b01e08dbb4d05be48f63"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d98/a00107.php#a1604ff5ed446b01e08dbb4d05be48f63">Quit</a> ()</td></tr>
<tr class="memdesc:a1604ff5ed446b01e08dbb4d05be48f63"><td class="mdescLeft">&#160;</td><td class="mdescRight">Quit the application.  <a href="#a1604ff5ed446b01e08dbb4d05be48f63">More...</a><br /></td></tr>
<tr class="separator:a1604ff5ed446b01e08dbb4d05be48f63"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:acbc4eaf9b9265fe9ac013aeba5e80e76"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d98/a00107.php#acbc4eaf9b9265fe9ac013aeba5e80e76">WindowTitleBar</a> (QWidget *parent=nullptr)</td></tr>
<tr class="memdesc:acbc4eaf9b9265fe9ac013aeba5e80e76"><td class="mdescLeft">&#160;</td><td class="mdescRight">The constructor.  <a href="#acbc4eaf9b9265fe9ac013aeba5e80e76">More...</a><br /></td></tr>
<tr class="separator:acbc4eaf9b9265fe9ac013aeba5e80e76"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8fa4e86180d7e76a04f68b864b5a8c3a"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d98/a00107.php#a8fa4e86180d7e76a04f68b864b5a8c3a">~WindowTitleBar</a> ()</td></tr>
<tr class="separator:a8fa4e86180d7e76a04f68b864b5a8c3a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pub_methods_a00095"><td colspan="2" onclick="javascript:toggleInherit('pub_methods_a00095')"><img src="../../closed.png" alt="-"/>&#160;Public Member Functions inherited from <a class="el" href="../../d9/d77/a00095.php">Widget</a></td></tr>
<tr class="memitem:ace1aa23652eb4425355a81760b39fd37 inherit pub_methods_a00095"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d9/d77/a00095.php#ace1aa23652eb4425355a81760b39fd37">Widget</a> (QWidget *parent=nullptr)</td></tr>
<tr class="memdesc:ace1aa23652eb4425355a81760b39fd37 inherit pub_methods_a00095"><td class="mdescLeft">&#160;</td><td class="mdescRight">Create a QWidget.  <a href="../../d9/d77/a00095.php#ace1aa23652eb4425355a81760b39fd37">More...</a><br /></td></tr>
<tr class="separator:ace1aa23652eb4425355a81760b39fd37 inherit pub_methods_a00095"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a714cf798aadb4d615f6f60a355382c02 inherit pub_methods_a00095"><td class="memItemLeft" align="right" valign="top">virtual&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d9/d77/a00095.php#a714cf798aadb4d615f6f60a355382c02">~Widget</a> ()</td></tr>
<tr class="separator:a714cf798aadb4d615f6f60a355382c02 inherit pub_methods_a00095"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pro-methods"></a>
Protected Member Functions</h2></td></tr>
<tr class="memitem:aade75345fb7a4b62c361345c64884a82"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d98/a00107.php#aade75345fb7a4b62c361345c64884a82">resizeEvent</a> (QResizeEvent *event)</td></tr>
<tr class="memdesc:aade75345fb7a4b62c361345c64884a82"><td class="mdescLeft">&#160;</td><td class="mdescRight">The resize event of the titlebar.  <a href="#aade75345fb7a4b62c361345c64884a82">More...</a><br /></td></tr>
<tr class="separator:aade75345fb7a4b62c361345c64884a82"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a43be58f98c5d53bce63cd96999e7c71a"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d98/a00107.php#a43be58f98c5d53bce63cd96999e7c71a">paintEvent</a> (QPaintEvent *event)</td></tr>
<tr class="memdesc:a43be58f98c5d53bce63cd96999e7c71a"><td class="mdescLeft">&#160;</td><td class="mdescRight">The paint event of the titlebar.  <a href="#a43be58f98c5d53bce63cd96999e7c71a">More...</a><br /></td></tr>
<tr class="separator:a43be58f98c5d53bce63cd96999e7c71a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a50b62b3569bb0e173904117cb875d157"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d98/a00107.php#a50b62b3569bb0e173904117cb875d157">mousePressEvent</a> (QMouseEvent *event)</td></tr>
<tr class="memdesc:a50b62b3569bb0e173904117cb875d157"><td class="mdescLeft">&#160;</td><td class="mdescRight">The mouse press event of the titlebar.  <a href="#a50b62b3569bb0e173904117cb875d157">More...</a><br /></td></tr>
<tr class="separator:a50b62b3569bb0e173904117cb875d157"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a5c3e48aa0d5bc65f2958b3037a0e1587"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d98/a00107.php#a5c3e48aa0d5bc65f2958b3037a0e1587">mouseReleaseEvent</a> (QMouseEvent *event)</td></tr>
<tr class="memdesc:a5c3e48aa0d5bc65f2958b3037a0e1587"><td class="mdescLeft">&#160;</td><td class="mdescRight">The mouse release event of the titlebar.  <a href="#a5c3e48aa0d5bc65f2958b3037a0e1587">More...</a><br /></td></tr>
<tr class="separator:a5c3e48aa0d5bc65f2958b3037a0e1587"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a5fa1f19401f127094ba42152928892a1"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d98/a00107.php#a5fa1f19401f127094ba42152928892a1">mouseMoveEvent</a> (QMouseEvent *event)</td></tr>
<tr class="memdesc:a5fa1f19401f127094ba42152928892a1"><td class="mdescLeft">&#160;</td><td class="mdescRight">The mouse move event of the titlebar.  <a href="#a5fa1f19401f127094ba42152928892a1">More...</a><br /></td></tr>
<tr class="separator:a5fa1f19401f127094ba42152928892a1"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a51c99fb3d787abe8bc647145272981f0"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d98/a00107.php#a51c99fb3d787abe8bc647145272981f0">drawTitleBar</a> (QPainter &amp;painter)</td></tr>
<tr class="memdesc:a51c99fb3d787abe8bc647145272981f0"><td class="mdescLeft">&#160;</td><td class="mdescRight">Draw the titlebar.  <a href="#a51c99fb3d787abe8bc647145272981f0">More...</a><br /></td></tr>
<tr class="separator:a51c99fb3d787abe8bc647145272981f0"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2929d886be76951491d9bb53a6e1ce9e"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../df/d98/a00107.php#a2929d886be76951491d9bb53a6e1ce9e">drawButtonsArea</a> (QPainter &amp;painter)</td></tr>
<tr class="memdesc:a2929d886be76951491d9bb53a6e1ce9e"><td class="mdescLeft">&#160;</td><td class="mdescRight">Draw the buttons area.  <a href="#a2929d886be76951491d9bb53a6e1ce9e">More...</a><br /></td></tr>
<tr class="separator:a2929d886be76951491d9bb53a6e1ce9e"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>The titlebar of the <a class="el" href="../../da/d74/a00099.php" title="A custom window. ">Window</a> class. </p>

<p class="definition">Definition at line <a class="el" href="../../d5/df9/a00044_source.php#l00018">18</a> of file <a class="el" href="../../d5/df9/a00044_source.php">WindowTitleBar.hpp</a>.</p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a id="acbc4eaf9b9265fe9ac013aeba5e80e76"></a>
<h2 class="memtitle"><span class="permalink"><a href="#acbc4eaf9b9265fe9ac013aeba5e80e76">&#9670;&nbsp;</a></span>WindowTitleBar()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">WindowTitleBar::WindowTitleBar </td>
          <td>(</td>
          <td class="paramtype">QWidget *&#160;</td>
          <td class="paramname"><em>parent</em> = <code>nullptr</code></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>The constructor. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">parent</td><td>The parent widget </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a id="a8fa4e86180d7e76a04f68b864b5a8c3a"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a8fa4e86180d7e76a04f68b864b5a8c3a">&#9670;&nbsp;</a></span>~WindowTitleBar()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">WindowTitleBar::~WindowTitleBar </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a id="a91ce1aab8c3ed4a14554a1ddc32a87f1"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a91ce1aab8c3ed4a14554a1ddc32a87f1">&#9670;&nbsp;</a></span>ApplyResizeChange</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void WindowTitleBar::ApplyResizeChange </td>
          <td>(</td>
          <td class="paramtype">bool&#160;</td>
          <td class="paramname"><em>state</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">slot</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Apply the resize state change. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">state</td><td>The state to save and apply </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

</div>
</div>
<a id="a4def0f2b659a07381fe8abaedd90e303"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a4def0f2b659a07381fe8abaedd90e303">&#9670;&nbsp;</a></span>ApplyTitleBarState</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void WindowTitleBar::ApplyTitleBarState </td>
          <td>(</td>
          <td class="paramtype">bool&#160;</td>
          <td class="paramname"><em>state</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">slot</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Show or hide the titlebar. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">state</td><td>The state to save and apply </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

</div>
</div>
<a id="a2929d886be76951491d9bb53a6e1ce9e"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a2929d886be76951491d9bb53a6e1ce9e">&#9670;&nbsp;</a></span>drawButtonsArea()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void WindowTitleBar::drawButtonsArea </td>
          <td>(</td>
          <td class="paramtype">QPainter &amp;&#160;</td>
          <td class="paramname"><em>painter</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Draw the buttons area. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">painter</td><td>The painter for the buttons area </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

</div>
</div>
<a id="a51c99fb3d787abe8bc647145272981f0"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a51c99fb3d787abe8bc647145272981f0">&#9670;&nbsp;</a></span>drawTitleBar()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void WindowTitleBar::drawTitleBar </td>
          <td>(</td>
          <td class="paramtype">QPainter &amp;&#160;</td>
          <td class="paramname"><em>painter</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Draw the titlebar. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">painter</td><td>The painter for the titlebar </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

</div>
</div>
<a id="a7d91818e1ef1189dc5c0524729a62e34"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a7d91818e1ef1189dc5c0524729a62e34">&#9670;&nbsp;</a></span>Maximized</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void WindowTitleBar::Maximized </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">slot</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Maximize the window. </p>

</div>
</div>
<a id="aae235853885d03ddd070efb8fef2f4e1"></a>
<h2 class="memtitle"><span class="permalink"><a href="#aae235853885d03ddd070efb8fef2f4e1">&#9670;&nbsp;</a></span>Minimized</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void WindowTitleBar::Minimized </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">slot</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Minimize the window. </p>

</div>
</div>
<a id="a5fa1f19401f127094ba42152928892a1"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a5fa1f19401f127094ba42152928892a1">&#9670;&nbsp;</a></span>mouseMoveEvent()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void WindowTitleBar::mouseMoveEvent </td>
          <td>(</td>
          <td class="paramtype">QMouseEvent *&#160;</td>
          <td class="paramname"><em>event</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>The mouse move event of the titlebar. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">event</td><td>The event to treat </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

</div>
</div>
<a id="a50b62b3569bb0e173904117cb875d157"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a50b62b3569bb0e173904117cb875d157">&#9670;&nbsp;</a></span>mousePressEvent()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void WindowTitleBar::mousePressEvent </td>
          <td>(</td>
          <td class="paramtype">QMouseEvent *&#160;</td>
          <td class="paramname"><em>event</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>The mouse press event of the titlebar. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">event</td><td>The event to treat </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

</div>
</div>
<a id="a5c3e48aa0d5bc65f2958b3037a0e1587"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a5c3e48aa0d5bc65f2958b3037a0e1587">&#9670;&nbsp;</a></span>mouseReleaseEvent()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void WindowTitleBar::mouseReleaseEvent </td>
          <td>(</td>
          <td class="paramtype">QMouseEvent *&#160;</td>
          <td class="paramname"><em>event</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>The mouse release event of the titlebar. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">event</td><td>The event to treat </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

</div>
</div>
<a id="a43be58f98c5d53bce63cd96999e7c71a"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a43be58f98c5d53bce63cd96999e7c71a">&#9670;&nbsp;</a></span>paintEvent()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void WindowTitleBar::paintEvent </td>
          <td>(</td>
          <td class="paramtype">QPaintEvent *&#160;</td>
          <td class="paramname"><em>event</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span><span class="mlabel">virtual</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>The paint event of the titlebar. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">event</td><td>The event to treat </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

<p>Reimplemented from <a class="el" href="../../d9/d77/a00095.php#a0ce51928b65b53bd72575e7138e3238c">Widget</a>.</p>

</div>
</div>
<a id="a1604ff5ed446b01e08dbb4d05be48f63"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a1604ff5ed446b01e08dbb4d05be48f63">&#9670;&nbsp;</a></span>Quit</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void WindowTitleBar::Quit </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">slot</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Quit the application. </p>

</div>
</div>
<a id="aade75345fb7a4b62c361345c64884a82"></a>
<h2 class="memtitle"><span class="permalink"><a href="#aade75345fb7a4b62c361345c64884a82">&#9670;&nbsp;</a></span>resizeEvent()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void WindowTitleBar::resizeEvent </td>
          <td>(</td>
          <td class="paramtype">QResizeEvent *&#160;</td>
          <td class="paramname"><em>event</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>The resize event of the titlebar. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">event</td><td>The event to treat </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

</div>
</div>
<a id="a5a96b7bd195f625fc4ffb6c7fe180709"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a5a96b7bd195f625fc4ffb6c7fe180709">&#9670;&nbsp;</a></span>UpdateWindowTitle</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void WindowTitleBar::UpdateWindowTitle </td>
          <td>(</td>
          <td class="paramtype">QString&#160;</td>
          <td class="paramname"><em>title</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">slot</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Update the window's title. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">title</td><td>The new title </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>void </dd></dl>

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li><a class="el" href="../../d5/df9/a00044_source.php">WindowTitleBar.hpp</a></li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="../../df/d98/a00107.php">WindowTitleBar</a></li>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.13 </li>
  </ul>
</div>
</body>
</html>
