<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.13"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>Qt: Class Hierarchy</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="resize.js"></script>
<script type="text/javascript" src="navtreedata.js"></script>
<script type="text/javascript" src="navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Qt
   &#160;<span id="projectnumber">1.0</span>
   </div>
   <div id="projectbrief">Specific widgets for Qt</div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('hierarchy.php','');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="headertitle">
<div class="title">Class Hierarchy</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock">
<p><a href="hierarchy.php">Go to the textual class hierarchy</a></p>
</div><table border="0" cellspacing="10" cellpadding="0">
<tr><td><img src="inherit_graph_0.png" border="0" alt="" usemap="#Font"/>
<map name="Font" id="Font">
<area shape="rect" id="node1" href="d4/d6d/a00055.php" title="A class to treat fonts with QFont. " alt="" coords="5,5,53,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_1.png" border="0" alt="" usemap="#Line"/>
<map name="Line" id="Line">
<area shape="rect" id="node2" href="d1/d6f/a00063.php" title="Create a line. " alt="" coords="123,31,169,57"/>
<area shape="rect" id="node3" href="dc/ddf/a00067.php" title="Create a horizontal line. " alt="" coords="217,5,273,32"/>
<area shape="rect" id="node4" href="d0/d89/a00071.php" title="Create a line. " alt="" coords="218,56,273,83"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_2.png" border="0" alt="" usemap="#QHSpacerItem"/>
<map name="QHSpacerItem" id="QHSpacerItem">
<area shape="rect" id="node2" href="d1/d51/a00079.php" title="An implementation of QSpacerItem. " alt="" coords="152,5,261,32"/>
<area shape="rect" id="node3" href="d2/d1f/a00083.php" title="An implementation of QSpacerItem. " alt="" coords="153,56,261,83"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_3.png" border="0" alt="" usemap="#Scene"/>
<map name="Scene" id="Scene">
<area shape="rect" id="node2" href="d9/da5/a00075.php" title="An implementation of QGraphcsScene with an updator. " alt="" coords="175,31,233,57"/>
<area shape="rect" id="node3" href="d2/d79/a00051.php" title="A Scene implementation to draw with tiles system. " alt="" coords="283,5,374,32"/>
<area shape="rect" id="node4" href="d3/d8b/a00059.php" title="A Scene implementation to draw graphs. " alt="" coords="281,56,376,83"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_4.png" border="0" alt="" usemap="#string"/>
<map name="string" id="string">
<area shape="rect" id="node1" href="d1/d1e/a00087.php" title="string" alt="" coords="5,29,60,56"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_5.png" border="0" alt="" usemap="#Widget"/>
<map name="Widget" id="Widget">
<area shape="rect" id="node1" href="da/d74/a00099.php" title="A custom window. " alt="" coords="5,31,75,57"/>
<area shape="rect" id="node2" href="d9/d77/a00095.php" title="Create a personnalized Widget. " alt="" coords="123,31,185,57"/>
<area shape="rect" id="node3" href="da/d82/a00091.php" title="Create a personnalized TableWidget. " alt="" coords="243,5,338,32"/>
<area shape="rect" id="node4" href="df/d98/a00107.php" title="The titlebar of the Window class. " alt="" coords="233,56,348,83"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_6.png" border="0" alt="" usemap="#WindowButton"/>
<map name="WindowButton" id="WindowButton">
<area shape="rect" id="node2" href="d5/d1e/a00103.php" title="The buttons for the WindowTitleBar and the Window. " alt="" coords="172,5,279,32"/>
</map>
</td></tr>
</table>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="doxygen.png" alt="doxygen"/></a> 1.8.13 </li>
  </ul>
</div>
</body>
</html>
