<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.13"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>Qt: TableWidget.hpp Source File</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Qt
   &#160;<span id="projectnumber">1.0</span>
   </div>
   <div id="projectbrief">Specific widgets for Qt</div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('dc/d87/a00032_source.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="headertitle">
<div class="title">TableWidget.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="../../dc/d87/a00032.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00008"></a><span class="lineno">    8</span>&#160;<span class="preprocessor">#ifndef HEADER_TABLE_WIDGET</span></div><div class="line"><a name="l00009"></a><span class="lineno">    9</span>&#160;<span class="preprocessor">#define HEADER_TABLE_WIDGET</span></div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;</div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;<span class="preprocessor">#include &lt;QtWidgets&gt;</span></div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;<span class="preprocessor">#include &quot;<a class="code" href="../../d2/de7/a00014.php">Qt.hpp</a>&quot;</span></div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;</div><div class="line"><a name="l00018"></a><span class="lineno"><a class="line" href="../../da/d82/a00091.php">   18</a></span>&#160;<span class="keyword">class </span><a class="code" href="../../da/d82/a00091.php">TableWidget</a> : <span class="keyword">public</span> <a class="code" href="../../d9/d77/a00095.php">Widget</a> {</div><div class="line"><a name="l00019"></a><span class="lineno">   19</span>&#160;    Q_OBJECT</div><div class="line"><a name="l00020"></a><span class="lineno">   20</span>&#160;    <span class="keyword">public</span>:</div><div class="line"><a name="l00022"></a><span class="lineno">   22</span>&#160;        <a class="code" href="../../da/d82/a00091.php#aa29e2c37c0e310779790537890c529f2">TableWidget</a>(QWidget* parent = <span class="keyword">nullptr</span>, <span class="keywordtype">size_t</span> w = 0, <span class="keywordtype">size_t</span> h = 0);</div><div class="line"><a name="l00023"></a><span class="lineno">   23</span>&#160;        <a class="code" href="../../da/d82/a00091.php#a5fb6edc429e21280d8f47faf6fe012fa">~TableWidget</a>();</div><div class="line"><a name="l00024"></a><span class="lineno">   24</span>&#160;</div><div class="line"><a name="l00030"></a><span class="lineno">   30</span>&#160;        <span class="keywordtype">void</span> <a class="code" href="../../da/d82/a00091.php#a9965d8f6b70b52fc8e25906a20d4a771">addHeader</a>(QWidget* widget);</div><div class="line"><a name="l00031"></a><span class="lineno">   31</span>&#160;</div><div class="line"><a name="l00039"></a><span class="lineno">   39</span>&#160;        <span class="keywordtype">void</span> <a class="code" href="../../da/d82/a00091.php#a9965d8f6b70b52fc8e25906a20d4a771">addHeader</a>(QWidget* widget, <span class="keywordtype">size_t</span> x);</div><div class="line"><a name="l00040"></a><span class="lineno">   40</span>&#160;</div><div class="line"><a name="l00048"></a><span class="lineno">   48</span>&#160;        <span class="keywordtype">void</span> <a class="code" href="../../da/d82/a00091.php#a25bba3124cdbe518985157ff23b0b1d0">setHeader</a>(QWidget* widget, <span class="keywordtype">size_t</span> x);</div><div class="line"><a name="l00049"></a><span class="lineno">   49</span>&#160;</div><div class="line"><a name="l00055"></a><span class="lineno">   55</span>&#160;        <span class="keywordtype">void</span> <a class="code" href="../../da/d82/a00091.php#abe173d2bf4af78a34eea42f6015dfc24">add</a>(QWidget* widget);</div><div class="line"><a name="l00061"></a><span class="lineno">   61</span>&#160;        <span class="keywordtype">void</span> <a class="code" href="../../da/d82/a00091.php#abe173d2bf4af78a34eea42f6015dfc24">add</a>(QCheckBox* widget);</div><div class="line"><a name="l00062"></a><span class="lineno">   62</span>&#160;</div><div class="line"><a name="l00071"></a><span class="lineno">   71</span>&#160;        <span class="keywordtype">void</span> <a class="code" href="../../da/d82/a00091.php#abe173d2bf4af78a34eea42f6015dfc24">add</a>(QWidget* widget, <span class="keywordtype">size_t</span> x, <span class="keywordtype">size_t</span> y);</div><div class="line"><a name="l00072"></a><span class="lineno">   72</span>&#160;</div><div class="line"><a name="l00081"></a><span class="lineno">   81</span>&#160;        <span class="keywordtype">void</span> <span class="keyword">set</span>(QWidget* widget, <span class="keywordtype">size_t</span> x, <span class="keywordtype">size_t</span> y);</div><div class="line"><a name="l00082"></a><span class="lineno">   82</span>&#160;</div><div class="line"><a name="l00084"></a><span class="lineno">   84</span>&#160;        <a class="code" href="../../da/d82/a00091.php">TableWidget</a>* <span class="keyword">get</span>(<span class="keywordtype">size_t</span> w = 0, <span class="keywordtype">size_t</span> h = 0);</div><div class="line"><a name="l00085"></a><span class="lineno">   85</span>&#160;</div><div class="line"><a name="l00086"></a><span class="lineno">   86</span>&#160;    <span class="keyword">public</span> slots:</div><div class="line"><a name="l00087"></a><span class="lineno">   87</span>&#160;        </div><div class="line"><a name="l00088"></a><span class="lineno">   88</span>&#160;</div><div class="line"><a name="l00089"></a><span class="lineno">   89</span>&#160;    signals:</div><div class="line"><a name="l00090"></a><span class="lineno">   90</span>&#160;        </div><div class="line"><a name="l00091"></a><span class="lineno">   91</span>&#160;</div><div class="line"><a name="l00092"></a><span class="lineno">   92</span>&#160;    <span class="keyword">protected</span>:</div><div class="line"><a name="l00094"></a><span class="lineno">   94</span>&#160;        <span class="keywordtype">void</span> <a class="code" href="../../da/d82/a00091.php#a8ee97e18b4afb72672b36ef2002537ae">update</a>();</div><div class="line"><a name="l00095"></a><span class="lineno">   95</span>&#160;</div><div class="line"><a name="l00096"></a><span class="lineno">   96</span>&#160;    <span class="keyword">private</span>:</div><div class="line"><a name="l00097"></a><span class="lineno">   97</span>&#160;        <span class="keywordtype">void</span> nextCell();</div><div class="line"><a name="l00098"></a><span class="lineno">   98</span>&#160;        <span class="keywordtype">void</span> deletions();</div><div class="line"><a name="l00099"></a><span class="lineno">   99</span>&#160;</div><div class="line"><a name="l00100"></a><span class="lineno">  100</span>&#160;        <span class="keywordtype">bool</span> isCheckbox(<span class="keywordtype">size_t</span> index);</div><div class="line"><a name="l00101"></a><span class="lineno">  101</span>&#160;</div><div class="line"><a name="l00102"></a><span class="lineno">  102</span>&#160;    <span class="keyword">private</span>:</div><div class="line"><a name="l00103"></a><span class="lineno">  103</span>&#160;                QHBoxLayout* headerContent;</div><div class="line"><a name="l00104"></a><span class="lineno">  104</span>&#160;            <a class="code" href="../../d9/d77/a00095.php">Widget</a>* headerContainer;</div><div class="line"><a name="l00105"></a><span class="lineno">  105</span>&#160;                        QGridLayout* grid;</div><div class="line"><a name="l00106"></a><span class="lineno">  106</span>&#160;                    QVBoxLayout* content;</div><div class="line"><a name="l00107"></a><span class="lineno">  107</span>&#160;                QWidget* container;</div><div class="line"><a name="l00108"></a><span class="lineno">  108</span>&#160;            QScrollArea* scroll;</div><div class="line"><a name="l00109"></a><span class="lineno">  109</span>&#160;        QVBoxLayout* center;</div><div class="line"><a name="l00110"></a><span class="lineno">  110</span>&#160;</div><div class="line"><a name="l00111"></a><span class="lineno">  111</span>&#160;        std::vector&lt;QWidget*&gt; widgets;</div><div class="line"><a name="l00112"></a><span class="lineno">  112</span>&#160;        std::vector&lt;QWidget*&gt; headers;</div><div class="line"><a name="l00113"></a><span class="lineno">  113</span>&#160;</div><div class="line"><a name="l00114"></a><span class="lineno">  114</span>&#160;        std::vector&lt;size_t&gt; checkboxs;</div><div class="line"><a name="l00115"></a><span class="lineno">  115</span>&#160;        std::vector&lt;size_t&gt; checkPerLine;</div><div class="line"><a name="l00116"></a><span class="lineno">  116</span>&#160;</div><div class="line"><a name="l00117"></a><span class="lineno">  117</span>&#160;        <span class="keywordtype">size_t</span> x;</div><div class="line"><a name="l00118"></a><span class="lineno">  118</span>&#160;        <span class="keywordtype">size_t</span> y;</div><div class="line"><a name="l00119"></a><span class="lineno">  119</span>&#160;</div><div class="line"><a name="l00120"></a><span class="lineno">  120</span>&#160;        <span class="keywordtype">size_t</span> w;</div><div class="line"><a name="l00121"></a><span class="lineno">  121</span>&#160;        <span class="keywordtype">size_t</span> h;</div><div class="line"><a name="l00122"></a><span class="lineno">  122</span>&#160;};</div><div class="line"><a name="l00123"></a><span class="lineno">  123</span>&#160;</div><div class="line"><a name="l00124"></a><span class="lineno">  124</span>&#160;<span class="preprocessor">#endif //HEADER_TABLE_WIDGET</span></div><div class="ttc" id="a00091_php_a9965d8f6b70b52fc8e25906a20d4a771"><div class="ttname"><a href="../../da/d82/a00091.php#a9965d8f6b70b52fc8e25906a20d4a771">TableWidget::addHeader</a></div><div class="ttdeci">void addHeader(QWidget *widget)</div></div>
<div class="ttc" id="a00095_php"><div class="ttname"><a href="../../d9/d77/a00095.php">Widget</a></div><div class="ttdoc">Create a personnalized Widget. </div><div class="ttdef"><b>Definition:</b> <a href="../../d4/d8c/a00035_source.php#l00017">Widget.hpp:17</a></div></div>
<div class="ttc" id="a00091_php_aa29e2c37c0e310779790537890c529f2"><div class="ttname"><a href="../../da/d82/a00091.php#aa29e2c37c0e310779790537890c529f2">TableWidget::TableWidget</a></div><div class="ttdeci">TableWidget(QWidget *parent=nullptr, size_t w=0, size_t h=0)</div><div class="ttdoc">Create a QGridLayout. </div></div>
<div class="ttc" id="a00091_php_abe173d2bf4af78a34eea42f6015dfc24"><div class="ttname"><a href="../../da/d82/a00091.php#abe173d2bf4af78a34eea42f6015dfc24">TableWidget::add</a></div><div class="ttdeci">void add(QWidget *widget)</div><div class="ttdoc">Add a widget to the table. </div></div>
<div class="ttc" id="a00014_php"><div class="ttname"><a href="../../d2/de7/a00014.php">Qt.hpp</a></div></div>
<div class="ttc" id="a00091_php_a5fb6edc429e21280d8f47faf6fe012fa"><div class="ttname"><a href="../../da/d82/a00091.php#a5fb6edc429e21280d8f47faf6fe012fa">TableWidget::~TableWidget</a></div><div class="ttdeci">~TableWidget()</div></div>
<div class="ttc" id="a00091_php"><div class="ttname"><a href="../../da/d82/a00091.php">TableWidget</a></div><div class="ttdoc">Create a personnalized TableWidget. </div><div class="ttdef"><b>Definition:</b> <a href="../../dc/d87/a00032_source.php#l00018">TableWidget.hpp:18</a></div></div>
<div class="ttc" id="a00091_php_a25bba3124cdbe518985157ff23b0b1d0"><div class="ttname"><a href="../../da/d82/a00091.php#a25bba3124cdbe518985157ff23b0b1d0">TableWidget::setHeader</a></div><div class="ttdeci">void setHeader(QWidget *widget, size_t x)</div></div>
<div class="ttc" id="a00091_php_a8ee97e18b4afb72672b36ef2002537ae"><div class="ttname"><a href="../../da/d82/a00091.php#a8ee97e18b4afb72672b36ef2002537ae">TableWidget::update</a></div><div class="ttdeci">void update()</div><div class="ttdoc">Update the grid layout. </div></div>
</div><!-- fragment --></div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="../../dir_badfd550b617ce52cc73ed1c8c9513f6.php">Algo</a></li><li class="navelem"><a class="el" href="../../dir_a02ca41573efbfa5a2fd3c2b5453f5e3.php">QTTests</a></li><li class="navelem"><a class="el" href="../../dir_241af41b803d499a248aecae0c64f982.php">Widgets</a></li><li class="navelem"><a class="el" href="../../dc/d87/a00032.php">TableWidget.hpp</a></li>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.13 </li>
  </ul>
</div>
</body>
</html>
