<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.13"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>Qt: TableWidget.hpp File Reference</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Qt
   &#160;<span id="projectnumber">1.0</span>
   </div>
   <div id="projectbrief">Specific widgets for Qt</div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('dc/d87/a00032.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#nested-classes">Classes</a>  </div>
  <div class="headertitle">
<div class="title">TableWidget.hpp File Reference</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock"><code>#include &lt;QtWidgets&gt;</code><br />
<code>#include &quot;<a class="el" href="../../d2/de7/a00014_source.php">Qt.hpp</a>&quot;</code><br />
</div><div class="textblock"><div class="dynheader">
Include dependency graph for TableWidget.hpp:</div>
<div class="dyncontent">
<div class="center"><img src="../../d0/dc0/a00033.png" border="0" usemap="#TableWidget_8hpp" alt=""/></div>
<map name="TableWidget_8hpp" id="TableWidget_8hpp">
<area shape="rect" id="node3" href="../../d2/de7/a00014.php" title="Qt.hpp" alt="" coords="149,80,210,107"/>
<area shape="rect" id="node4" href="../../d4/d51/a00017.php" title="QtDefines.hpp" alt="" coords="583,379,690,405"/>
<area shape="rect" id="node19" href="../../d8/d41/a00038.php" title="Window.hpp" alt="" coords="188,155,283,181"/>
<area shape="rect" id="node22" href="../../d5/d16/a00029.php" title="String.hpp" alt="" coords="83,155,164,181"/>
<area shape="rect" id="node23" href="../../da/d45/a00011.php" title="Lines.hpp" alt="" coords="5,229,84,256"/>
<area shape="rect" id="node5" href="../../d4/d8c/a00035.php" title="Widget.hpp" alt="" coords="514,528,602,555"/>
<area shape="rect" id="node6" href="../../d7/d46/a00002.php" title="DrawScene.hpp" alt="" coords="1122,453,1237,480"/>
<area shape="rect" id="node7" href="../../d3/d52/a00023.php" title="Scene.hpp" alt="" coords="1237,528,1321,555"/>
<area shape="rect" id="node9" href="../../d4/dee/a00008.php" title="GraphScene.hpp" alt="" coords="972,453,1091,480"/>
<area shape="rect" id="node14" href="../../d6/d5b/a00026.php" title="Spacers.hpp" alt="" coords="589,453,684,480"/>
<area shape="rect" id="node15" href="../../db/db2/a00020.php" title="QtFunctions.hpp" alt="" coords="708,453,827,480"/>
<area shape="rect" id="node17" href="../../dd/dad/a00005.php" title="Font.hpp" alt="" coords="851,453,924,480"/>
<area shape="rect" id="node20" href="../../d5/df9/a00044.php" title="WindowTitleBar.hpp" alt="" coords="283,229,422,256"/>
<area shape="rect" id="node21" href="../../dd/d32/a00041.php" title="WindowButton.hpp" alt="" coords="413,304,545,331"/>
</map>
</div>
</div><div class="textblock"><div class="dynheader">
This graph shows which files directly or indirectly include this file:</div>
<div class="dyncontent">
<div class="center"><img src="../../db/df3/a00034.png" border="0" usemap="#TableWidget_8hppdep" alt=""/></div>
<map name="TableWidget_8hppdep" id="TableWidget_8hppdep">
<area shape="rect" id="node2" href="../../d2/de7/a00014.php" title="Qt.hpp" alt="" coords="35,80,96,107"/>
<area shape="rect" id="node3" href="../../d5/d16/a00029.php" title="String.hpp" alt="" coords="25,155,106,181"/>
</map>
</div>
</div>
<p><a href="../../dc/d87/a00032_source.php">Go to the source code of this file.</a></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="nested-classes"></a>
Classes</h2></td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../da/d82/a00091.php">TableWidget</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">Create a personnalized <a class="el" href="../../da/d82/a00091.php" title="Create a personnalized TableWidget. ">TableWidget</a>.  <a href="../../da/d82/a00091.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><dl class="section author"><dt>Author</dt><dd>Mathias CABIOCH-DELALANDE </dd></dl>
<dl class="section date"><dt>Date</dt><dd>09 juin 2018 </dd></dl>

<p class="definition">Definition in file <a class="el" href="../../dc/d87/a00032_source.php">TableWidget.hpp</a>.</p>
</div></div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="../../dir_badfd550b617ce52cc73ed1c8c9513f6.php">Algo</a></li><li class="navelem"><a class="el" href="../../dir_a02ca41573efbfa5a2fd3c2b5453f5e3.php">QTTests</a></li><li class="navelem"><a class="el" href="../../dir_241af41b803d499a248aecae0c64f982.php">Widgets</a></li><li class="navelem"><a class="el" href="../../dc/d87/a00032.php">TableWidget.hpp</a></li>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.13 </li>
  </ul>
</div>
</body>
</html>
