<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.13"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>Qt: QtFunctions.hpp File Reference</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../dynsections.js"></script>
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtreedata.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/searchdata.js"></script>
<script type="text/javascript" src="../../search/search.js"></script>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Qt
   &#160;<span id="projectnumber">1.0</span>
   </div>
   <div id="projectbrief">Specific widgets for Qt</div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
<script type="text/javascript" src="../../menudata.js"></script>
<script type="text/javascript" src="../../menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('../../',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('db/db2/a00020.php','../../');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#typedef-members">Typedefs</a> &#124;
<a href="#func-members">Functions</a>  </div>
  <div class="headertitle">
<div class="title">QtFunctions.hpp File Reference</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock"><code>#include &lt;QtWidgets&gt;</code><br />
<code>#include &quot;C++/defines.hpp&quot;</code><br />
</div><div class="textblock"><div class="dynheader">
Include dependency graph for QtFunctions.hpp:</div>
<div class="dyncontent">
<div class="center"><img src="../../de/d11/a00021.png" border="0" usemap="#QtFunctions_8hpp" alt=""/></div>
</div>
</div><div class="textblock"><div class="dynheader">
This graph shows which files directly or indirectly include this file:</div>
<div class="dyncontent">
<div class="center"><img src="../../d7/de0/a00022.png" border="0" usemap="#QtFunctions_8hppdep" alt=""/></div>
<map name="QtFunctions_8hppdep" id="QtFunctions_8hppdep">
<area shape="rect" id="node2" href="../../d4/d51/a00017.php" title="QtDefines.hpp" alt="" coords="84,80,191,107"/>
<area shape="rect" id="node3" href="../../d2/de7/a00014.php" title="Qt.hpp" alt="" coords="97,379,159,405"/>
<area shape="rect" id="node6" href="../../dd/d32/a00041.php" title="WindowButton.hpp" alt="" coords="125,155,257,181"/>
<area shape="rect" id="node4" href="../../dc/d87/a00032.php" title="TableWidget.hpp" alt="" coords="5,453,125,480"/>
<area shape="rect" id="node5" href="../../d5/d16/a00029.php" title="String.hpp" alt="" coords="150,453,231,480"/>
<area shape="rect" id="node7" href="../../d5/df9/a00044.php" title="WindowTitleBar.hpp" alt="" coords="123,229,261,256"/>
<area shape="rect" id="node8" href="../../d8/d41/a00038.php" title="Window.hpp" alt="" coords="134,304,229,331"/>
</map>
</div>
</div>
<p><a href="../../db/db2/a00020_source.php">Go to the source code of this file.</a></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="typedef-members"></a>
Typedefs</h2></td></tr>
<tr class="memitem:ae996d9afaef5cea512610eaca0b204e4"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/db2/a00020.php#ae996d9afaef5cea512610eaca0b204e4">QtWindow</a> = mcd::ContraptionAttr</td></tr>
<tr class="memdesc:ae996d9afaef5cea512610eaca0b204e4"><td class="mdescLeft">&#160;</td><td class="mdescRight">An alias for Qt.  <a href="#ae996d9afaef5cea512610eaca0b204e4">More...</a><br /></td></tr>
<tr class="separator:ae996d9afaef5cea512610eaca0b204e4"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="func-members"></a>
Functions</h2></td></tr>
<tr class="memitem:a0272cd6761e50151f46337d1d7f793f2"><td class="memItemLeft" align="right" valign="top"><a class="el" href="../../db/db2/a00020.php#ae996d9afaef5cea512610eaca0b204e4">QtWindow</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/db2/a00020.php#a0272cd6761e50151f46337d1d7f793f2">getDesktopSize</a> ()</td></tr>
<tr class="memdesc:a0272cd6761e50151f46337d1d7f793f2"><td class="mdescLeft">&#160;</td><td class="mdescRight">Get the size of the desktop.  <a href="#a0272cd6761e50151f46337d1d7f793f2">More...</a><br /></td></tr>
<tr class="separator:a0272cd6761e50151f46337d1d7f793f2"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7a5b8564155df959a2ed36b171090ec2"><td class="memItemLeft" align="right" valign="top">size_t&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/db2/a00020.php#a7a5b8564155df959a2ed36b171090ec2">getDesktopWidth</a> ()</td></tr>
<tr class="memdesc:a7a5b8564155df959a2ed36b171090ec2"><td class="mdescLeft">&#160;</td><td class="mdescRight">Get the width of the desktop.  <a href="#a7a5b8564155df959a2ed36b171090ec2">More...</a><br /></td></tr>
<tr class="separator:a7a5b8564155df959a2ed36b171090ec2"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4e89aa67e6219267f0f2965567c447a5"><td class="memItemLeft" align="right" valign="top">size_t&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/db2/a00020.php#a4e89aa67e6219267f0f2965567c447a5">getDesktopHeight</a> ()</td></tr>
<tr class="memdesc:a4e89aa67e6219267f0f2965567c447a5"><td class="mdescLeft">&#160;</td><td class="mdescRight">Get the height of the desktop.  <a href="#a4e89aa67e6219267f0f2965567c447a5">More...</a><br /></td></tr>
<tr class="separator:a4e89aa67e6219267f0f2965567c447a5"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac35a8acbe17be1d705ecf8d940eacc95"><td class="memItemLeft" align="right" valign="top">std::string&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../db/db2/a00020.php#ac35a8acbe17be1d705ecf8d940eacc95">cssReader</a> (std::string path)</td></tr>
<tr class="memdesc:ac35a8acbe17be1d705ecf8d940eacc95"><td class="mdescLeft">&#160;</td><td class="mdescRight">Read a Cascade Style Sheet and translate it for Qt.  <a href="#ac35a8acbe17be1d705ecf8d940eacc95">More...</a><br /></td></tr>
<tr class="separator:ac35a8acbe17be1d705ecf8d940eacc95"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><dl class="section author"><dt>Author</dt><dd>Mathias CABIOCH-DELALANDE </dd></dl>
<dl class="section date"><dt>Date</dt><dd>02 juin 2018 </dd></dl>

<p class="definition">Definition in file <a class="el" href="../../db/db2/a00020_source.php">QtFunctions.hpp</a>.</p>
</div><h2 class="groupheader">Typedef Documentation</h2>
<a id="ae996d9afaef5cea512610eaca0b204e4"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ae996d9afaef5cea512610eaca0b204e4">&#9670;&nbsp;</a></span>QtWindow</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="../../db/db2/a00020.php#ae996d9afaef5cea512610eaca0b204e4">QtWindow</a> =  mcd::ContraptionAttr</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>An alias for Qt. </p>

<p class="definition">Definition at line <a class="el" href="../../db/db2/a00020_source.php#l00016">16</a> of file <a class="el" href="../../db/db2/a00020_source.php">QtFunctions.hpp</a>.</p>

</div>
</div>
<h2 class="groupheader">Function Documentation</h2>
<a id="ac35a8acbe17be1d705ecf8d940eacc95"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ac35a8acbe17be1d705ecf8d940eacc95">&#9670;&nbsp;</a></span>cssReader()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">std::string cssReader </td>
          <td>(</td>
          <td class="paramtype">std::string&#160;</td>
          <td class="paramname"><em>path</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Read a Cascade Style Sheet and translate it for Qt. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">path</td><td>The path to the file </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>Return the file contents as a string </dd></dl>

</div>
</div>
<a id="a4e89aa67e6219267f0f2965567c447a5"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a4e89aa67e6219267f0f2965567c447a5">&#9670;&nbsp;</a></span>getDesktopHeight()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">size_t getDesktopHeight </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Get the height of the desktop. </p>

</div>
</div>
<a id="a0272cd6761e50151f46337d1d7f793f2"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a0272cd6761e50151f46337d1d7f793f2">&#9670;&nbsp;</a></span>getDesktopSize()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="../../db/db2/a00020.php#ae996d9afaef5cea512610eaca0b204e4">QtWindow</a> getDesktopSize </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Get the size of the desktop. </p>
<dl class="section return"><dt>Returns</dt><dd>Return a QtWindow struct </dd></dl>

</div>
</div>
<a id="a7a5b8564155df959a2ed36b171090ec2"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a7a5b8564155df959a2ed36b171090ec2">&#9670;&nbsp;</a></span>getDesktopWidth()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">size_t getDesktopWidth </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Get the width of the desktop. </p>

</div>
</div>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="../../dir_badfd550b617ce52cc73ed1c8c9513f6.php">Algo</a></li><li class="navelem"><a class="el" href="../../dir_a02ca41573efbfa5a2fd3c2b5453f5e3.php">QTTests</a></li><li class="navelem"><a class="el" href="../../dir_241af41b803d499a248aecae0c64f982.php">Widgets</a></li><li class="navelem"><a class="el" href="../../db/db2/a00020.php">QtFunctions.hpp</a></li>
    <li class="footer">Generated by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.8.13 </li>
  </ul>
</div>
</body>
</html>
